export const averagesTopic = {
  slug: 'averages',
  title: 'Averages',
  tagline: "Why is average speed NOT just (speed1 + speed2) / 2? Follow Arjun's cricket scores through every classic Averages trap.",
  sections: [
    {
      id: 'story',
      title: 'The Story',
      subsections: [
        {
          id: 'arjuns-scores',
          title: "Arjun's Cricket Scores",
          type: 'concept',
          videoUrl: '',
          explanation: [
            'Arjun scores 40, 50, and 60 runs in his first 3 matches. His average score is (40 + 50 + 60) ÷ 3 = 50 runs per match.',
            'Average = Sum of all values ÷ Number of values. That single formula is the base of every question in this topic — the 5 patterns below are really just this formula wearing different disguises.',
          ],
        },
      ],
    },
    {
      id: 'equation-based',
      title: 'Based on Equation',
      subsections: [
        {
          id: 'equation-based-questions',
          title: 'Working Backwards From the Average',
          type: 'animation',
          animationKey: 'equationBased',
          videoUrl: '',
          explanation: [
            "Most exam questions don't ask you to calculate an average — they GIVE you the average and ask you to find a missing piece. Since Average = Sum ÷ Count, you can always rearrange it to Sum = Average × Count.",
            "Once you have the total sum, finding one missing value is just subtraction: missing value = required total sum − sum of the known values.",
          ],
        },
      ],
    },
    {
      id: 'true-false-reading',
      title: 'True or False Reading',
      subsections: [
        {
          id: 'true-false-statements',
          title: 'Judging Statements About an Average',
          type: 'animation',
          animationKey: 'trueFalseReading',
          videoUrl: '',
          explanation: [
            "This question type doesn't ask you to calculate anything — it gives you a set of numbers (or facts about them) and a statement, and asks whether the statement MUST be true.",
            'The one rule that answers almost all of these: the average of a set always lies between its smallest and largest values — it can never be less than the minimum or more than the maximum.',
            'Read statements against that rule before doing any arithmetic — most "True or False" questions are testing whether you know this boundary, not whether you can add fast.',
          ],
        },
      ],
    },
    {
      id: 'replacing-person',
      title: 'Replacing a Person',
      subsections: [
        {
          id: 'replacing-a-person',
          title: 'One Person Swapped for Another',
          type: 'animation',
          animationKey: 'replacingPerson',
          videoUrl: '',
          explanation: [
            'Classic setup: a group\'s average changes because ONE member is replaced by someone else. You\'re usually asked to find the new (or old) person\'s value.',
            "Don't recompute everything from scratch. Shortcut: the new person's value = the old person's value + (change in average × number of people). This works because the entire shift in the total is caused by just that one swap.",
          ],
        },
      ],
    },
    {
      id: 'including-excluding',
      title: 'Including and Excluding',
      subsections: [
        {
          id: 'including-excluding-members',
          title: 'A Member Joins or Leaves the Group',
          type: 'animation',
          animationKey: 'includingExcluding',
          videoUrl: '',
          explanation: [
            "Similar to replacing a person, but here the GROUP SIZE itself changes — someone joins (included) or someone leaves (excluded), instead of a one-for-one swap.",
            "When someone joins: new person's value = new average + (number of OLD members × change in average).",
            'When someone leaves: excluded value = old average − (number of REMAINING members × change in average). The sign flips because removing a below-average member raises the average, and vice versa — always sanity-check your answer against that direction.',
          ],
        },
      ],
    },
    {
      id: 'average-speed',
      title: 'Average Speed',
      subsections: [
        {
          id: 'average-speed-trap',
          title: 'The Classic Trap: Same Distance, Different Speeds',
          type: 'animation',
          animationKey: 'averageSpeed',
          videoUrl: '',
          explanation: [
            'The single most common mistake in this entire topic: when you travel the SAME distance at two different speeds (e.g. going and returning), the average speed is NOT (speed1 + speed2) ÷ 2.',
            'Why not? Because average speed is defined as TOTAL DISTANCE ÷ TOTAL TIME — and you spend MORE time traveling at the slower speed, so the slower speed pulls the average down more than a simple midpoint would suggest.',
            'For equal distances: Average speed = (2 × speed1 × speed2) ÷ (speed1 + speed2). This only applies when the DISTANCES are equal — if instead the TIMES are equal, the simple arithmetic average (speed1 + speed2) ÷ 2 is actually correct. Always check which one is equal before picking a formula.',
          ],
        },
      ],
    },
  ],
  practiceQuestions: [
    {
      id: 'q1',
      question: "Average of 5 numbers is 27. If one number is excluded, the average of the remaining 4 becomes 25. What was the excluded number?",
      options: ['35', '25', '30', '40'],
      correctIndex: 0,
      explanation: 'Sum of 5 = 27×5 = 135. Sum of remaining 4 = 25×4 = 100. Excluded number = 135 − 100 = 35.',
    },
    {
      id: 'q2',
      question: 'Which statement about the average of a set of numbers is always true?',
      options: [
        'It lies between the smallest and largest values',
        'It always equals the median',
        'It is always greater than every value in the set',
        'It is always less than every value in the set',
      ],
      correctIndex: 0,
      explanation: 'The average can never fall below the minimum or above the maximum of the set.',
    },
    {
      id: 'q3',
      question: 'Average age of 8 people is 25. A person aged 22 leaves and is replaced by a new person, and the average becomes 26. What is the new person\'s age?',
      options: ['30', '28', '32', '26'],
      correctIndex: 0,
      explanation: 'Change in total = (26 − 25) × 8 = 8. New person\'s age = 22 + 8 = 30.',
    },
    {
      id: 'q4',
      question: 'Average marks of 20 students is 60. A new student joins and the average becomes 61. What are the new student\'s marks?',
      options: ['81', '61', '80', '100'],
      correctIndex: 0,
      explanation: "New student's marks = new average + (old count × change) = 61 + (20 × 1) = 81.",
    },
    {
      id: 'q5',
      question: 'A car travels at 30 km/h going and 50 km/h returning over the same route. What is its average speed for the round trip?',
      options: ['37.5 km/h', '40 km/h', '45 km/h', '50 km/h'],
      correctIndex: 0,
      explanation: 'Equal distances → average speed = (2 × 30 × 50) ÷ (30 + 50) = 3000 ÷ 80 = 37.5 km/h.',
    },
  ],
  practiceBank: {
    level1: [
      { id: 'av-l1-1', question: 'Find the average of 10, 20, and 30.', options: ['15', '20', '25', '30'], correctIndex: 1, explanation: '(10+20+30)/3 = 20.' },
      { id: 'av-l1-2', question: 'The average of 4 numbers is 15. Find their sum.', options: ['45', '50', '60', '75'], correctIndex: 2, explanation: 'Sum = average × count = 15×4 = 60.' },
      { id: 'av-l1-3', question: 'Find the average of the first 5 natural numbers (1,2,3,4,5).', options: ['2', '2.5', '3', '3.5'], correctIndex: 2, explanation: 'Sum=15, count=5, average=3.' },
      { id: 'av-l1-4', question: 'The average of 5 numbers is 18. Four of them are 10, 15, 20, and 25. Find the fifth.', options: ['15', '18', '20', '25'], correctIndex: 2, explanation: 'Sum needed=90. Known sum=70. Fifth=20.' },
      { id: 'av-l1-5', question: 'Find the average of 12, 18, 24, and 30.', options: ['19', '20', '21', '22'], correctIndex: 2, explanation: '(12+18+24+30)/4 = 84/4 = 21.' },
      { id: 'av-l1-6', question: 'The average weight of 6 boys is 45 kg. Find their total weight.', options: ['240 kg', '250 kg', '260 kg', '270 kg'], correctIndex: 3, explanation: 'Total = 45×6 = 270 kg.' },
      { id: 'av-l1-7', question: 'Find the average of the first 10 even numbers (2,4,...,20).', options: ['9', '10', '11', '12'], correctIndex: 2, explanation: 'Sum=110, count=10, average=11.' },
      { id: 'av-l1-8', question: 'The average marks of 3 students is 70. Two of them scored 65 and 75. Find the third\'s marks.', options: ['65', '68', '70', '72'], correctIndex: 2, explanation: 'Sum needed=210. Known sum=140. Third=70.' },
      { id: 'av-l1-9', question: 'Find the average of 15, 25, 35, 45, and 55.', options: ['30', '32', '35', '38'], correctIndex: 2, explanation: '(15+25+35+45+55)/5 = 175/5 = 35.' },
      { id: 'av-l1-10', question: 'The average of 8 numbers is 20. Find their total sum.', options: ['140', '150', '160', '170'], correctIndex: 2, explanation: 'Sum = 20×8 = 160.' },
      { id: 'av-l1-11', question: 'Find the average of the first 5 odd numbers (1,3,5,7,9).', options: ['3', '4', '5', '6'], correctIndex: 2, explanation: 'Sum=25, count=5, average=5.' },
      { id: 'av-l1-12', question: 'The average of two numbers is 25. If one number is 30, find the other.', options: ['15', '18', '20', '22'], correctIndex: 2, explanation: 'Sum=50. Other = 50−30=20.' },
      { id: 'av-l1-13', question: 'Find the average speed of a car that travels 100 km in 2 hours (constant speed).', options: ['40 km/h', '45 km/h', '50 km/h', '55 km/h'], correctIndex: 2, explanation: 'Speed = distance/time = 100/2 = 50 km/h.' },
      { id: 'av-l1-14', question: 'The average of 6 numbers is 12. The sum of 5 of them is 55. Find the sixth.', options: ['15', '17', '19', '21'], correctIndex: 1, explanation: 'Total sum=72. Sixth = 72−55=17.' },
      { id: 'av-l1-15', question: 'Find the average of 7, 14, 21, and 28.', options: ['16.5', '17.5', '18.5', '19.5'], correctIndex: 1, explanation: '(7+14+21+28)/4 = 70/4 = 17.5.' },
    ],
    level2: [
      { id: 'av-l2-1', question: 'The average of 5 numbers is 20. Which of these could NOT be the largest number in the set?', options: ['15', '20', '25', '30'], correctIndex: 0, explanation: 'The largest value can never be below the average — 15 < 20 is impossible.' },
      { id: 'av-l2-2', question: 'The average of a set of numbers is 45. Which of these could NOT be the smallest number in the set?', options: ['30', '45', '50', '60'], correctIndex: 3, explanation: 'The smallest value can never exceed the average — 60 > 45 is impossible.' },
      { id: 'av-l2-3', question: 'Average age of 7 people is 28. One person aged 25 leaves and a new person joins, making the new average 30. Find the new person\'s age.', options: ['35', '37', '39', '41'], correctIndex: 2, explanation: 'Change in total = (30−28)×7 = 14. New person = 25+14 = 39.' },
      { id: 'av-l2-4', question: 'Average height of a class of 25 students is 150 cm. A new student joins and the average becomes 151 cm. Find the new student\'s height.', options: ['170 cm', '173 cm', '176 cm', '179 cm'], correctIndex: 2, explanation: 'New total=151×26=3926. Old total=150×25=3750. New student=176 cm.' },
      { id: 'av-l2-5', question: 'Average marks of 10 students is 60. One student\'s marks are excluded and the average drops to 58. Find the excluded marks.', options: ['72', '75', '78', '80'], correctIndex: 2, explanation: 'Sum10=600. Sum9=522. Excluded = 600−522 = 78.' },
      { id: 'av-l2-6', question: 'Average weight of a group of 8 people is 65 kg. A person weighing 70 kg leaves. Find the new average (to 1 decimal).', options: ['63.4 kg', '63.9 kg', '64.3 kg', '64.9 kg'], correctIndex: 2, explanation: 'Remaining total = 8×65−70 = 450. New average = 450/7 ≈ 64.3 kg.' },
      { id: 'av-l2-7', question: 'A man travels at 20 km/h going and 30 km/h returning over the same route. Find his average speed.', options: ['22 km/h', '24 km/h', '25 km/h', '26 km/h'], correctIndex: 1, explanation: 'Equal distances: (2×20×30)/(20+30) = 1200/50 = 24 km/h.' },
      { id: 'av-l2-8', question: 'A train covers a distance at 60 km/h and returns at 40 km/h. Find the average speed for the entire trip.', options: ['46 km/h', '47 km/h', '48 km/h', '50 km/h'], correctIndex: 2, explanation: 'Equal distances: (2×60×40)/(60+40) = 4800/100 = 48 km/h.' },
      { id: 'av-l2-9', question: 'Average score of a batsman in 10 innings is 42. In the 11th innings he scores 86. Find his new average.', options: ['44', '45', '46', '47'], correctIndex: 2, explanation: 'New total=420+86=506. New average=506/11=46.' },
      { id: 'av-l2-10', question: 'The average of 6 numbers is 25. Two numbers, 20 and 30, are removed. Find the average of the remaining 4.', options: ['22.5', '24', '25', '26.5'], correctIndex: 2, explanation: 'Sum6=150. Removed sum=50. Remaining sum=100, average=100/4=25 (unchanged, since removed numbers averaged 25 too).' },
      { id: 'av-l2-11', question: 'Average age of a class of 40 students is 16 years. If the teacher\'s age (45) is included, find the new average (to 1 decimal).', options: ['16.5', '16.7', '16.9', '17.1'], correctIndex: 1, explanation: 'New total=640+45=685. New average=685/41≈16.7 years.' },
      { id: 'av-l2-12', question: 'A car travels the first half of a journey at 40 km/h and the second half (equal distance) at 60 km/h. Find the average speed.', options: ['46 km/h', '47 km/h', '48 km/h', '50 km/h'], correctIndex: 2, explanation: 'Equal distances: (2×40×60)/(40+60) = 4800/100 = 48 km/h.' },
      { id: 'av-l2-13', question: 'The average of 4 numbers is 35. One number is replaced by a new number, and the average increases by 5. Find the increase in that number\'s value.', options: ['15', '18', '20', '25'], correctIndex: 2, explanation: 'Change in total = 5×4 = 20 — the replaced number increased by 20.' },
      { id: 'av-l2-14', question: 'Average weight of 20 students is 55 kg. 5 students leave, and the average of the remaining 15 becomes 54 kg. Find the average weight of the 5 who left.', options: ['56 kg', '57 kg', '58 kg', '59 kg'], correctIndex: 2, explanation: 'Total20=1100. Remaining15=810. Left5=290, average=58 kg.' },
      { id: 'av-l2-15', question: 'Average marks of a class of 50 is 65. If 10 students with an average of 80 are removed, find the new average of the remaining 40.', options: ['60.25', '61.25', '62.25', '63.25'], correctIndex: 1, explanation: 'Total50=3250. Removed10=800. Remaining40=2450, average=61.25.' },
    ],
    level3: [
      { id: 'av-l3-1', question: 'The average of 11 numbers is 60. The average of the first 6 is 58, and the last 6 is 63. Find the 6th number (common to both groups).', options: ['62', '64', '66', '68'], correctIndex: 2, explanation: 'Sum11=660. Sum(first6)+Sum(last6)=348+378=726, which double-counts the 6th number. 6th = 726−660 = 66.' },
      { id: 'av-l3-2', question: 'The average age of a husband, wife, and child 3 years ago was 27. The average age of wife and child 5 years ago was 20. Find the husband\'s present age.', options: ['36', '38', '40', '42'], correctIndex: 2, explanation: '3yrs ago sum=81 → present sum=90. 5yrs ago (W+C)=40 → present (W+C)=50. Husband=90−50=40.' },
      { id: 'av-l3-3', question: 'A cricketer\'s average increases by 8 runs after scoring 100 in his 10th innings. Find his new average.', options: ['24', '26', '28', '30'], correctIndex: 2, explanation: 'Let old average=x. 9x+100=10(x+8) → x=20. New average = 28.' },
      { id: 'av-l3-4', question: 'Average temperature Mon–Thu is 48°C, and Tue–Fri is 52°C. If Monday\'s temperature is 42°C, find Friday\'s temperature.', options: ['54°C', '56°C', '58°C', '60°C'], correctIndex: 2, explanation: 'Sum(Mon-Thu)=192, Sum(Tue-Fri)=208. Friday−Monday=16. Friday=42+16=58°C.' },
      { id: 'av-l3-5', question: 'The average of three numbers is 14. The first is twice the second, and the second is twice the third. Find the largest number.', options: ['20', '22', '24', '26'], correctIndex: 2, explanation: 'Let third=x, second=2x, first=4x. Sum=7x=42 → x=6. Largest=4x=24.' },
      { id: 'av-l3-6', question: 'The average of 5 consecutive odd numbers is 61. Find the largest number.', options: ['63', '65', '67', '69'], correctIndex: 1, explanation: 'For consecutive numbers, the average equals the middle term = 61. Largest = 61+4 = 65.' },
      { id: 'av-l3-7', question: 'In a group of 6 people, the average weight increases by 2.5 kg when a 60 kg person is replaced. Find the new person\'s weight.', options: ['70 kg', '72 kg', '75 kg', '78 kg'], correctIndex: 2, explanation: 'Change in total = 2.5×6 = 15. New weight = 60+15 = 75 kg.' },
      { id: 'av-l3-8', question: 'The average of 20 numbers is 0. At most how many of them can be negative?', options: ['10', '15', '19', '20'], correctIndex: 2, explanation: 'If all 20 were negative, the sum couldn\'t be 0. At most 19 can be negative, balanced by one large positive number.' },
      { id: 'av-l3-9', question: 'The average score of a class of 30 in a test is 70. One student\'s score was wrongly recorded as 60 instead of 90. Find the correct average.', options: ['70', '70.5', '71', '71.5'], correctIndex: 2, explanation: 'Corrected sum = 2100+(90−60) = 2130. Corrected average = 2130/30 = 71.' },
      { id: 'av-l3-10', question: 'The average of A and B is 45, of B and C is 55, and of A and C is 50. Find the average of A, B, and C together.', options: ['45', '48', '50', '52'], correctIndex: 2, explanation: 'Sum of all pairwise sums = 2(A+B+C) = 90+110+100 = 300 → A+B+C=150 → average=50.' },
    ],
  },
};
