export const probabilityTopic = {
  slug: 'probability',
  title: 'Probability',
  tagline: "Why do we divide by the total? Why multiply sometimes and add other times? Follow Priya's bag of marbles to see the logic.",
  sections: [
    {
      id: 'story',
      title: 'The Story',
      subsections: [
        {
          id: 'the-bag',
          title: "Priya's Bag of Marbles",
          type: 'concept',
          videoUrl: '',
          explanation: [
            'Priya has a bag with 5 marbles: 3 red and 2 blue. She reaches in without looking and picks one out.',
            'Question: what is the CHANCE that she picks a red marble?',
            "Probability is just a fraction that measures chance: how many outcomes count as a \"win\" for what we're asking about, out of how many outcomes are possible in total. Once you can count both of those correctly, every probability question becomes the same simple division.",
          ],
        },
      ],
    },
    {
      id: 'basic-probability',
      title: 'Basic Probability',
      subsections: [
        {
          id: 'favorable-over-total',
          title: 'Favorable Outcomes ÷ Total Outcomes',
          type: 'animation',
          animationKey: 'basicProbability',
          videoUrl: '',
          explanation: [
            "\"Favorable outcomes\" means the outcomes we actually care about — here, picking a red marble. There are 3 of them.",
            '"Total outcomes" means every possible thing that could happen — here, picking any one of the 5 marbles, red or blue.',
            'P(red) = favorable ÷ total = 3/5 = 0.6, or 60%. That\'s it — that fraction IS the probability. Every harder probability question is really just this same idea, applied to a trickier count.',
          ],
        },
      ],
    },
    {
      id: 'combining-events',
      title: 'Combining Two Events',
      subsections: [
        {
          id: 'and-rule',
          title: 'AND Rule — Independent Events',
          type: 'animation',
          animationKey: 'andRule',
          videoUrl: '',
          explanation: [
            "Now suppose Priya picks a marble AND separately rolls a die, wanting BOTH a red marble AND a 6. These two events don't affect each other at all — that's called INDEPENDENT.",
            "Here's the intuition for why we MULTIPLY instead of add: for every 5 possible marble outcomes, there are 6 possible die outcomes attached to EACH one — so there are 5 × 6 = 30 total combined outcomes. Out of those, only 3 × 1 = 3 combinations give her both a red marble and a 6.",
            'So P(red AND 6) = P(red) × P(6) = 3/5 × 1/6 = 3/30 = 1/10.',
            "Rule of thumb: when a question uses the word \"AND\" for two events that don't affect each other, multiply their probabilities.",
          ],
        },
        {
          id: 'or-rule',
          title: 'OR Rule — Mutually Exclusive Events',
          type: 'animation',
          animationKey: 'orRule',
          videoUrl: '',
          explanation: [
            "Different situation now: Priya rolls ONE die and wants to know the chance of getting a 2 OR a 5. These two outcomes can NEVER both happen on the same roll — that's called MUTUALLY EXCLUSIVE.",
            "Here's why we ADD instead of multiply: out of the 6 faces, 1 face is a win for \"getting a 2\" and a different 1 face is a win for \"getting a 5\" — since they never overlap, the two winning groups just combine into 1 + 1 = 2 winning faces out of 6.",
            'So P(2 OR 5) = P(2) + P(5) = 1/6 + 1/6 = 2/6 = 1/3.',
            "Rule of thumb: when a question uses the word \"OR\" for two outcomes that can't both happen at once, add their probabilities.",
          ],
        },
      ],
    },
    {
      id: 'cards-dice',
      title: 'Cards & Dice',
      subsections: [
        {
          id: 'classic-setups',
          title: 'The Classic Exam Setups',
          type: 'concept',
          videoUrl: '',
          explanation: [
            'Most aptitude probability questions reuse the same few "total outcomes" counts — memorizing these saves time:',
            'A single die roll: 6 total outcomes (faces 1–6).',
            'Two dice rolled together: 6 × 6 = 36 total outcomes.',
            'A single coin toss: 2 total outcomes (Heads, Tails). Two coins together: 2 × 2 = 4 total outcomes.',
            'A standard deck of playing cards: 52 total outcomes — 4 suits × 13 cards each, including 4 Kings, 4 Queens, 4 Jacks, and 4 Aces.',
            '(Full animated walkthroughs for cards and dice combinations coming in a future update.)',
          ],
        },
      ],
    },
  ],
  practiceQuestions: [
    {
      id: 'q1',
      question: 'A bag has 4 red and 6 blue balls. What is the probability of picking a red ball?',
      options: ['2/5', '3/5', '4/6', '1/10'],
      correctIndex: 0,
      explanation: 'Favorable = 4 red, total = 10 balls. P(red) = 4/10 = 2/5.',
    },
    {
      id: 'q2',
      question: 'Two fair coins are tossed together. What is the probability that BOTH show Heads?',
      options: ['1/4', '1/2', '1', '1/3'],
      correctIndex: 0,
      explanation: 'Independent events — multiply: P(H) × P(H) = 1/2 × 1/2 = 1/4.',
    },
    {
      id: 'q3',
      question: 'A die is rolled once. What is the probability of getting a number greater than 4?',
      options: ['1/3', '1/6', '2/3', '1/2'],
      correctIndex: 0,
      explanation: 'Numbers greater than 4 on a die: 5 and 6 — that\'s 2 favorable out of 6. P = 2/6 = 1/3.',
    },
    {
      id: 'q4',
      question: 'A card is drawn from a standard 52-card deck. What is the probability it is a King OR a Queen?',
      options: ['2/13', '1/13', '4/13', '8/13'],
      correctIndex: 0,
      explanation: 'Mutually exclusive — add: 4 Kings + 4 Queens = 8 favorable out of 52. P = 8/52 = 2/13.',
    },
    {
      id: 'q5',
      question: 'P(A) = 0.3 and P(B) = 0.5, and A and B are mutually exclusive. What is P(A or B)?',
      options: ['0.8', '0.15', '0.2', '1.5'],
      correctIndex: 0,
      explanation: 'Mutually exclusive events — add the probabilities directly: 0.3 + 0.5 = 0.8.',
    },
  ],
  practiceBank: {
    level1: [
      { id: 'pr-l1-1', question: 'A single die is rolled. What is the probability of getting a 4?', options: ['1/4', '1/6', '1/3', '1/2'], correctIndex: 1, explanation: '1 favorable outcome out of 6 faces.' },
      { id: 'pr-l1-2', question: 'A coin is tossed once. What is the probability of getting Heads?', options: ['1/4', '1/3', '1/2', '1'], correctIndex: 2, explanation: '1 favorable out of 2 outcomes.' },
      { id: 'pr-l1-3', question: 'A bag contains 5 red and 3 blue balls. What is the probability of picking a red ball?', options: ['3/8', '5/8', '1/2', '5/3'], correctIndex: 1, explanation: '5 favorable out of 8 total.' },
      { id: 'pr-l1-4', question: 'A card is drawn from a standard deck of 52. What is the probability that it is a King?', options: ['1/13', '1/26', '4/13', '1/52'], correctIndex: 0, explanation: '4 Kings out of 52 = 4/52 = 1/13.' },
      { id: 'pr-l1-5', question: 'A die is rolled. What is the probability of getting an even number?', options: ['1/3', '1/2', '2/3', '1/6'], correctIndex: 1, explanation: 'Even faces: 2,4,6 → 3/6 = 1/2.' },
      { id: 'pr-l1-6', question: 'A bag has 4 white and 6 black balls. What is the probability of picking a black ball?', options: ['2/5', '3/5', '4/10', '1/2'], correctIndex: 1, explanation: '6 favorable out of 10 = 3/5.' },
      { id: 'pr-l1-7', question: 'Two coins are tossed. What is the probability of getting exactly one Head?', options: ['1/4', '1/2', '3/4', '1/3'], correctIndex: 1, explanation: 'Outcomes: HH,HT,TH,TT. Exactly one Head: HT,TH → 2/4 = 1/2.' },
      { id: 'pr-l1-8', question: 'A die is rolled. What is the probability of getting a number less than 3?', options: ['1/6', '1/3', '1/2', '2/3'], correctIndex: 1, explanation: 'Favorable: 1,2 → 2/6 = 1/3.' },
      { id: 'pr-l1-9', question: 'A card is drawn from a deck of 52. What is the probability it is a Heart?', options: ['1/13', '1/4', '13/52', 'Both B and C'], correctIndex: 3, explanation: '13 Hearts out of 52 = 13/52 = 1/4 — both B and C are the same value.' },
      { id: 'pr-l1-10', question: 'A bag has 10 balls numbered 1 to 10. What is the probability of drawing an even-numbered ball?', options: ['2/5', '1/2', '3/5', '1/10'], correctIndex: 1, explanation: '5 even numbers out of 10 = 1/2.' },
      { id: 'pr-l1-11', question: 'A die is rolled. What is the probability of NOT getting a 6?', options: ['1/6', '1/3', '1/2', '5/6'], correctIndex: 3, explanation: '1 − 1/6 = 5/6.' },
      { id: 'pr-l1-12', question: 'A bag contains 2 red, 3 green, and 5 blue balls. What is the probability of picking a green ball?', options: ['1/5', '3/10', '1/2', '2/5'], correctIndex: 1, explanation: '3 favorable out of 10 = 3/10.' },
      { id: 'pr-l1-13', question: 'A card is drawn from a deck. What is the probability it is an Ace?', options: ['1/13', '1/26', '1/52', '4/13'], correctIndex: 0, explanation: '4 Aces out of 52 = 1/13.' },
      { id: 'pr-l1-14', question: 'A die is rolled twice. What is the probability of getting a 6 on the FIRST roll?', options: ['1/6', '1/12', '1/36', '1/3'], correctIndex: 0, explanation: 'The first roll alone: 1/6, unaffected by the second roll.' },
      { id: 'pr-l1-15', question: 'A bag has 7 red and 3 blue marbles. What is the probability of picking a blue marble?', options: ['7/10', '3/10', '3/7', '1/3'], correctIndex: 1, explanation: '3 favorable out of 10 = 3/10.' },
    ],
    level2: [
      { id: 'pr-l2-1', question: 'Two dice are rolled together. What is the probability that the sum is 7?', options: ['1/12', '1/9', '1/6', '5/36'], correctIndex: 2, explanation: '6 favorable pairs out of 36 = 1/6.' },
      { id: 'pr-l2-2', question: 'A card is drawn from a deck. What is the probability it is a King or a Queen?', options: ['2/13', '1/13', '4/13', '8/13'], correctIndex: 0, explanation: 'Mutually exclusive — 4+4=8 favorable out of 52 = 2/13.' },
      { id: 'pr-l2-3', question: 'Two coins are tossed. What is the probability of getting at least one Head?', options: ['1/4', '1/2', '3/4', '1'], correctIndex: 2, explanation: '1 − P(no heads) = 1 − 1/4 = 3/4.' },
      { id: 'pr-l2-4', question: 'A bag has 4 red and 6 blue balls. Two balls are drawn one after another WITH replacement. Find P(both red).', options: ['2/5', '4/25', '2/25', '4/10'], correctIndex: 1, explanation: '(4/10)×(4/10) = 16/100 = 4/25.' },
      { id: 'pr-l2-5', question: 'A die is rolled twice. What is the probability of getting a 6 both times?', options: ['1/6', '1/12', '1/36', '1/18'], correctIndex: 2, explanation: '1/6 × 1/6 = 1/36.' },
      { id: 'pr-l2-6', question: 'A bag has 3 red and 7 blue balls. What is the probability of NOT picking a red ball?', options: ['3/10', '7/10', '1/3', '3/7'], correctIndex: 1, explanation: '7 favorable (non-red) out of 10 = 7/10.' },
      { id: 'pr-l2-7', question: 'Two dice are rolled. What is the probability that the sum is either 8 or 9?', options: ['1/6', '5/18', '1/4', '7/36'], correctIndex: 2, explanation: 'Sum of 8: 5 ways, sum of 9: 4 ways. Total = 9/36 = 1/4.' },
      { id: 'pr-l2-8', question: 'A card is drawn from a deck. What is the probability it is a red card or a King?', options: ['7/13', '1/2', '28/52', 'Both A and C'], correctIndex: 3, explanation: 'Red=26, Kings=4, overlap (red Kings)=2. Total=26+4−2=28/52=7/13 — both A and C match.' },
      { id: 'pr-l2-9', question: 'A bag has 5 red and 5 blue balls. Two balls are drawn WITHOUT replacement. Find P(both red).', options: ['1/4', '2/9', '5/18', '1/2'], correctIndex: 1, explanation: '(5/10)×(4/9) = 20/90 = 2/9.' },
      { id: 'pr-l2-10', question: 'A die is rolled. What is the probability of getting a number that is a multiple of 3?', options: ['1/6', '1/3', '1/2', '2/3'], correctIndex: 1, explanation: 'Favorable: 3,6 → 2/6 = 1/3.' },
      { id: 'pr-l2-11', question: 'Two coins are tossed. What is the probability of getting NO Heads?', options: ['1/4', '1/2', '3/4', '1'], correctIndex: 0, explanation: 'Only TT out of 4 outcomes = 1/4.' },
      { id: 'pr-l2-12', question: 'A bag has 6 red and 4 blue balls. One ball is drawn, replaced, and another drawn. Find P(first red, second blue).', options: ['3/25', '6/25', '2/5', '4/25'], correctIndex: 1, explanation: '(6/10)×(4/10) = 24/100 = 6/25.' },
      { id: 'pr-l2-13', question: 'Three coins are tossed together. What is the probability of getting exactly two Heads?', options: ['1/8', '1/4', '3/8', '1/2'], correctIndex: 2, explanation: '3 favorable outcomes (HHT, HTH, THH) out of 8 = 3/8.' },
      { id: 'pr-l2-14', question: 'A card is drawn from a deck. What is the probability it is NEITHER a King nor a Queen?', options: ['8/52', '44/52', '2/13', '11/13'], correctIndex: 3, explanation: '1 − 8/52 = 44/52 = 11/13.' },
      { id: 'pr-l2-15', question: 'A bag contains 4 red, 3 blue, and 3 green balls. What is the probability of picking a ball that is NOT green?', options: ['3/10', '7/10', '4/10', '1/2'], correctIndex: 1, explanation: '7 non-green out of 10 = 7/10.' },
    ],
    level3: [
      { id: 'pr-l3-1', question: 'A bag has 5 red and 4 blue balls. Two balls are drawn without replacement. Find the probability that both are the SAME color.', options: ['4/9', '5/9', '1/2', '7/18'], correctIndex: 0, explanation: 'P(both red)+P(both blue) = (5/9×4/8)+(4/9×3/8) = 20/72+12/72 = 32/72 = 4/9.' },
      { id: 'pr-l3-2', question: 'A committee of 3 is selected from 5 men and 4 women. Find the probability it has exactly 2 men and 1 woman.', options: ['5/21', '10/21', '2/7', '3/7'], correctIndex: 1, explanation: 'C(5,2)×C(4,1) / C(9,3) = 10×4/84 = 40/84 = 10/21.' },
      { id: 'pr-l3-3', question: 'From a deck of 52 cards, 2 cards are drawn without replacement. Find P(both are Aces).', options: ['1/169', '1/221', '1/13', '4/221'], correctIndex: 1, explanation: '(4/52)×(3/51) = 12/2652 = 1/221.' },
      { id: 'pr-l3-4', question: 'A bag has 6 red and 4 black balls. Three balls are drawn without replacement. Find P(all three red).', options: ['1/8', '1/6', '1/5', '3/20'], correctIndex: 1, explanation: '(6/10)×(5/9)×(4/8) = 120/720 = 1/6.' },
      { id: 'pr-l3-5', question: 'Two dice are thrown. Find the probability that the PRODUCT of the numbers shown is 12.', options: ['1/12', '1/9', '1/6', '5/36'], correctIndex: 1, explanation: 'Pairs giving product 12: (2,6)(3,4)(4,3)(6,2) = 4 out of 36 = 1/9.' },
      { id: 'pr-l3-6', question: 'In a class of 30, 18 play cricket, 12 play football, and 5 play both. Find P(a random student plays NEITHER).', options: ['1/6', '1/5', '5/30', 'Both A and C'], correctIndex: 3, explanation: 'Playing at least one = 18+12−5=25. Neither = 5/30 = 1/6 — A and C are the same value.' },
      { id: 'pr-l3-7', question: 'A bag has 3 red, 4 blue, and 5 green balls. Two balls are drawn without replacement. Find P(both blue).', options: ['1/11', '1/12', '2/11', '1/9'], correctIndex: 0, explanation: '(4/12)×(3/11) = 12/132 = 1/11.' },
      { id: 'pr-l3-8', question: 'A fair die is rolled 3 times. Find the probability of getting a 6 at least once.', options: ['91/216', '125/216', '1/216', '5/6'], correctIndex: 0, explanation: '1 − (5/6)³ = 1 − 125/216 = 91/216.' },
      { id: 'pr-l3-9', question: 'Two cards are drawn from a deck without replacement. Find the probability that both are of the SAME suit.', options: ['1/4', '4/17', '1/17', '13/51'], correctIndex: 1, explanation: 'After the first card, 12 of the remaining 51 cards match its suit: 12/51 = 4/17.' },
      { id: 'pr-l3-10', question: 'A box has 6 defective and 14 non-defective bulbs. Two bulbs are drawn without replacement. Find P(both non-defective).', options: ['91/190', '7/10', '13/19', '49/100'], correctIndex: 0, explanation: '(14/20)×(13/19) = 182/380 = 91/190.' },
    ],
  },
};
