export const ratioProportionTopic = {
  slug: 'ratio-and-proportion',
  title: 'Ratio & Proportion',
  tagline: "How do you split a profit fairly when two people invested different amounts? Follow Arjun and Kumar's juice shop to see the logic.",
  sections: [
    {
      id: 'story',
      title: 'The Story',
      subsections: [
        {
          id: 'juice-shop',
          title: "Arjun and Kumar's Juice Shop",
          type: 'concept',
          videoUrl: '',
          explanation: [
            'Arjun invests ₹30,000 and Kumar invests ₹20,000 to start a juice shop together. At the end of the year, they make a profit of ₹5,000.',
            "Question: how should they split the profit FAIRLY? Not equally — Arjun put in more money, so he should get a bigger share.",
            'The fair way is to split it in the same RATIO as their investment: 30,000 : 20,000, which simplifies to 3 : 2. Ratio is just a way of comparing two quantities by division instead of subtraction — and once two ratios are set equal to each other, that\'s called a PROPORTION.',
          ],
        },
      ],
    },
    {
      id: 'what-is-ratio',
      title: 'What is a Ratio?',
      subsections: [
        {
          id: 'ratio-basics',
          title: 'Comparing Two Quantities',
          type: 'concept',
          videoUrl: '',
          explanation: [
            'A ratio a:b compares two quantities by division — it just means a ÷ b, written without doing the division. 30,000:20,000 simplifies the same way a fraction does: divide both sides by their HCF (10,000) to get 3:2.',
            "A ratio has no units — 3:2 could mean rupees, kilometers, or people, as long as both sides are measured in the SAME unit. That's why you must convert units to match before writing a ratio (e.g. 50 cm to 2 m must become 50 cm : 200 cm, not 50:2).",
          ],
        },
      ],
    },
    {
      id: 'dividing-ratio',
      title: 'Dividing a Quantity in a Given Ratio',
      subsections: [
        {
          id: 'splitting-the-profit',
          title: 'Splitting ₹5,000 in the Ratio 3:2',
          type: 'animation',
          animationKey: 'dividingRatio',
          videoUrl: '',
          explanation: [
            'To split any amount in a given ratio, first add the parts of the ratio together to find the TOTAL number of parts. For 3:2, that\'s 3+2 = 5 parts.',
            'Then find the value of ONE part: total amount ÷ total parts. Finally, multiply that one-part value by each person\'s share of the ratio.',
            "This same technique works for splitting anything in any ratio — money, ages, ingredients, angles — the parts-based logic never changes.",
          ],
        },
      ],
    },
    {
      id: 'proportion',
      title: 'Proportion',
      subsections: [
        {
          id: 'solving-proportion',
          title: 'When Two Ratios Are Equal',
          type: 'animation',
          animationKey: 'proportionSolve',
          videoUrl: '',
          explanation: [
            'A proportion says two ratios are equal: a:b = c:d (also written a:b :: c:d). If any three of the four values are known, the fourth (called the FOURTH PROPORTIONAL) can always be found.',
            'The shortcut is CROSS MULTIPLICATION: a:b = c:d means a×d = b×c. Whichever value is missing, isolate it using this cross-multiplied equation.',
            "Related idea — MEAN PROPORTIONAL: if a:b = b:c, then b is called the mean proportional between a and c, and b = √(a×c). This comes from the same cross-multiplication rule: a×c = b×b = b².",
          ],
        },
      ],
    },
    {
      id: 'compound-ratio',
      title: 'Compound Ratio',
      subsections: [
        {
          id: 'combining-two-ratios',
          title: 'Chaining A:B and B:C Into A:B:C',
          type: 'animation',
          animationKey: 'compoundRatio',
          videoUrl: '',
          explanation: [
            "Real problems often give you two SEPARATE ratios that share a common term — like A:B and B:C — and ask for the combined A:B:C. You can't just glue them together, because B might be a different NUMBER of parts in each ratio.",
            "The fix: scale both ratios so B matches in both — using the LCM of B's two values, exactly like the LCM topic. Once B is the same number on both sides, A:B:C reads off directly.",
          ],
        },
      ],
    },
    {
      id: 'direct-inverse',
      title: 'Direct & Inverse Proportion',
      subsections: [
        {
          id: 'direct-inverse-proportion',
          title: 'When Things Increase Together vs Opposite Each Other',
          type: 'concept',
          videoUrl: '',
          explanation: [
            'DIRECT proportion: as one quantity increases, the other increases at the same rate too (e.g. more pens cost more money — cost and quantity move together). Formula: if x and y are directly proportional, x/y stays constant.',
            'INVERSE proportion: as one quantity increases, the other DECREASES (e.g. more workers finish a job faster — workers and days move opposite ways). Formula: if x and y are inversely proportional, x × y stays constant.',
            "The exam giveaway: \"more of X needs more of Y\" → direct. \"More of X needs less of Y\" (or finishes faster/slower) → inverse. Misreading which one applies is the most common mistake in this pattern.",
          ],
        },
      ],
    },
  ],
  practiceQuestions: [
    {
      id: 'qc1',
      question: 'Simplify the ratio 12:18.',
      options: ['3:4', '2:3', '4:5', '1:2'],
      correctIndex: 1,
      explanation: 'HCF(12,18) = 6. 12÷6 : 18÷6 = 2:3.',
    },
    {
      id: 'qc2',
      question: 'Divide ₹300 in the ratio 1:2. Find the larger share.',
      options: ['100', '150', '200', '250'],
      correctIndex: 2,
      explanation: 'Total parts = 3. Value per part = 100. Larger share = 2×100 = 200.',
    },
    {
      id: 'qc3',
      question: 'Find x if 5:x = 10:20.',
      options: ['8', '10', '12', '15'],
      correctIndex: 1,
      explanation: 'Cross multiply: 5×20 = 10×x → x = 10.',
    },
    {
      id: 'qc4',
      question: 'Find the mean proportional between 9 and 16.',
      options: ['10', '11', '12', '13'],
      correctIndex: 2,
      explanation: 'Mean proportional = √(9×16) = √144 = 12.',
    },
    {
      id: 'qc5',
      question: 'If a:b = 2:5 and a = 8, find b.',
      options: ['16', '18', '20', '22'],
      correctIndex: 2,
      explanation: 'a/b = 2/5 → 8/b = 2/5 → b = 8×5/2 = 20.',
    },
  ],
  practiceBank: {
    level1: [
      { id: 'rp-l1-1', question: 'Simplify the ratio 8:12.', options: ['1:2', '2:3', '3:4', '4:5'], correctIndex: 1, explanation: 'HCF(8,12)=4. 8÷4:12÷4 = 2:3.' },
      { id: 'rp-l1-2', question: 'Express the ratio 15:20 in simplest form.', options: ['2:3', '3:4', '4:5', '5:6'], correctIndex: 1, explanation: 'HCF(15,20)=5. 15÷5:20÷5 = 3:4.' },
      { id: 'rp-l1-3', question: 'If a:b = 3:5 and b = 25, find a.', options: ['10', '12', '15', '18'], correctIndex: 2, explanation: 'a/25 = 3/5 → a = 15.' },
      { id: 'rp-l1-4', question: 'Divide ₹200 in the ratio 2:3. Find the smaller share.', options: ['₹60', '₹70', '₹80', '₹90'], correctIndex: 2, explanation: 'Total parts=5, unit=40. Smaller share = 2×40 = ₹80.' },
      { id: 'rp-l1-5', question: 'Find the ratio of 25 to 75.', options: ['1:2', '1:3', '1:4', '2:3'], correctIndex: 1, explanation: 'HCF(25,75)=25 → 25:75 = 1:3.' },
      { id: 'rp-l1-6', question: 'If 4:x = 8:16, find x.', options: ['6', '7', '8', '9'], correctIndex: 2, explanation: 'Cross multiply: 4×16 = 8×x → x = 8.' },
      { id: 'rp-l1-7', question: 'Simplify the ratio 45:60.', options: ['2:3', '3:4', '4:5', '5:6'], correctIndex: 1, explanation: 'HCF(45,60)=15 → 45:60 = 3:4.' },
      { id: 'rp-l1-8', question: 'Two numbers are in the ratio 5:7. If the smaller is 30, find the larger.', options: ['35', '38', '40', '42'], correctIndex: 3, explanation: 'Unit = 30÷5 = 6. Larger = 7×6 = 42.' },
      { id: 'rp-l1-9', question: 'Find the ratio of 1.5 to 4.5.', options: ['1:2', '1:3', '1:4', '2:3'], correctIndex: 1, explanation: '1.5:4.5 = 1:3.' },
      { id: 'rp-l1-10', question: 'If a:b = 2:3 and b:c = 3:4, find a:c.', options: ['1:2', '2:3', '3:4', '1:3'], correctIndex: 0, explanation: 'Since b matches (3 in both), a:c = 2:4 = 1:2.' },
      { id: 'rp-l1-11', question: 'Divide 60 into two parts in the ratio 1:2. Find the larger part.', options: ['20', '30', '40', '50'], correctIndex: 2, explanation: 'Total parts=3, unit=20. Larger = 2×20 = 40.' },
      { id: 'rp-l1-12', question: 'Express 3/4 as a ratio.', options: ['4:3', '3:4', '3:7', '4:7'], correctIndex: 1, explanation: 'A fraction a/b is the ratio a:b, so 3/4 = 3:4.' },
      { id: 'rp-l1-13', question: 'If x:y = 4:9 and y = 45, find x.', options: ['16', '18', '20', '22'], correctIndex: 2, explanation: 'x/45 = 4/9 → x = 20.' },
      { id: 'rp-l1-14', question: 'Find the ratio of 50 cm to 2 meters.', options: ['1:2', '1:4', '1:5', '1:8'], correctIndex: 1, explanation: '2 m = 200 cm. 50:200 = 1:4.' },
      { id: 'rp-l1-15', question: 'Simplify the ratio 100:250.', options: ['1:2', '2:5', '3:5', '2:3'], correctIndex: 1, explanation: 'HCF(100,250)=50 → 100:250 = 2:5.' },
    ],
    level2: [
      { id: 'rp-l2-1', question: 'Find the fourth proportional to 3, 6, and 8. (3:6 :: 8:x)', options: ['12', '14', '16', '18'], correctIndex: 2, explanation: '3/6 = 8/x → x = 8×6/3 = 16.' },
      { id: 'rp-l2-2', question: 'Find the third proportional to 4 and 8. (4:8 :: 8:x)', options: ['12', '14', '16', '18'], correctIndex: 2, explanation: '4/8 = 8/x → x = 64/4 = 16.' },
      { id: 'rp-l2-3', question: 'Find the mean proportional between 4 and 16.', options: ['6', '7', '8', '9'], correctIndex: 2, explanation: '√(4×16) = √64 = 8.' },
      { id: 'rp-l2-4', question: 'If A:B = 3:4 and B:C = 5:6, find A:B:C.', options: ['15:20:24', '12:16:20', '9:12:15', '6:8:10'], correctIndex: 0, explanation: 'Match B (LCM of 4,5=20): A:B=15:20, B:C=20:24 → A:B:C = 15:20:24.' },
      { id: 'rp-l2-5', question: 'Two numbers are in the ratio 4:5. If their sum is 90, find the smaller number.', options: ['35', '38', '40', '42'], correctIndex: 2, explanation: 'Total parts=9, unit=10. Smaller = 4×10 = 40.' },
      { id: 'rp-l2-6', question: 'If 12 workers can build a wall in 6 days, how many days will 8 workers take (assuming equal work rate)?', options: ['7', '8', '9', '10'], correctIndex: 2, explanation: 'Inverse proportion: 12×6 = 8×d → d = 9 days.' },
      { id: 'rp-l2-7', question: 'If the cost of 5 pens is ₹75, find the cost of 8 pens.', options: ['₹100', '₹110', '₹120', '₹130'], correctIndex: 2, explanation: 'Direct proportion: 75/5=15 per pen. 8×15 = ₹120.' },
      { id: 'rp-l2-8', question: 'Divide ₹720 among A, B, and C in the ratio 2:3:4. Find B\'s share.', options: ['₹200', '₹220', '₹240', '₹260'], correctIndex: 2, explanation: 'Total parts=9, unit=80. B = 3×80 = ₹240.' },
      { id: 'rp-l2-9', question: 'If a:b = 5:6 and a = 25, find b.', options: ['28', '30', '32', '34'], correctIndex: 1, explanation: 'a/b = 5/6 → 25/b = 5/6 → b = 30.' },
      { id: 'rp-l2-10', question: 'The ratio of boys to girls in a class is 3:2. If there are 15 boys, find the number of girls.', options: ['8', '9', '10', '11'], correctIndex: 2, explanation: 'Unit = 15/3 = 5. Girls = 2×5 = 10.' },
      { id: 'rp-l2-11', question: 'Find the compound ratio of 2:3 and 4:5.', options: ['6:8', '8:15', '6:15', '8:12'], correctIndex: 1, explanation: 'Compound ratio multiplies term-by-term: (2×4):(3×5) = 8:15.' },
      { id: 'rp-l2-12', question: 'If 15 men can complete a task in 12 days, how many men are needed to complete it in 9 days?', options: ['18', '20', '22', '24'], correctIndex: 1, explanation: 'Inverse proportion: 15×12 = 9×m → m = 20.' },
      { id: 'rp-l2-13', question: 'A sum of ₹1500 is divided between X and Y in the ratio 7:8. Find X\'s share.', options: ['₹650', '₹700', '₹750', '₹800'], correctIndex: 1, explanation: 'Total parts=15, unit=100. X = 7×100 = ₹700.' },
      { id: 'rp-l2-14', question: 'If x:y = 2:3 and y:z = 4:5, find x:y:z.', options: ['8:12:15', '6:9:12', '4:6:10', '2:3:5'], correctIndex: 0, explanation: 'Match y (LCM of 3,4=12): x:y=8:12, y:z=12:15 → x:y:z = 8:12:15.' },
      { id: 'rp-l2-15', question: 'The ratio of two numbers is 7:9 and their HCF is 4. Find the larger number.', options: ['28', '32', '36', '40'], correctIndex: 2, explanation: 'Since HCF=4, numbers = 7×4=28 and 9×4=36. Larger = 36.' },
    ],
    level3: [
      { id: 'rp-l3-1', question: 'In a sum of money, A gets half of what B and C together get, and B gets one-third of what A and C together get. Find A:B:C.', options: ['2:1:1', '4:3:5', '3:4:5', '5:3:4'], correctIndex: 1, explanation: 'Solving 2A=B+C and 3B=A+C together gives A:B:C = 4:3:5.' },
      { id: 'rp-l3-2', question: 'Two numbers are in the ratio 3:4. If 6 is added to both, the ratio becomes 4:5. Find the larger original number.', options: ['20', '22', '24', '26'], correctIndex: 2, explanation: 'Let numbers=3x,4x. (3x+6)/(4x+6)=4/5 → x=6. Larger = 4×6 = 24.' },
      { id: 'rp-l3-3', question: 'Incomes of A and B are in ratio 5:4, and expenditures are in ratio 3:2. If each saves ₹1000, find A\'s income.', options: ['₹2000', '₹2200', '₹2500', '₹2800'], correctIndex: 2, explanation: 'Solving 5k−3m=1000 and 4k−2m=1000 gives k=500. A\'s income = 5×500 = ₹2500.' },
      { id: 'rp-l3-4', question: 'A bag has ₹1 and 50-paise coins in the ratio 3:5. If the total value is ₹275, find the number of ₹1 coins.', options: ['120', '135', '150', '165'], correctIndex: 2, explanation: 'Let coins=3x,5x. Value=3x+2.5x=5.5x=275 → x=50. ₹1 coins = 3×50=150.' },
      { id: 'rp-l3-5', question: 'If a:b = 3:4 and b:c = 8:9, find a:c.', options: ['1:2', '2:3', '3:4', '5:6'], correctIndex: 1, explanation: 'Match b (LCM of 4,8=8): a:b=6:8, b:c=8:9 → a:c = 6:9 = 2:3.' },
      { id: 'rp-l3-6', question: 'The ratio of present ages of A and B is 5:7. After 6 years, the ratio becomes 3:4. Find A\'s present age.', options: ['24', '27', '30', '33'], correctIndex: 2, explanation: 'Let ages=5x,7x. (5x+6)/(7x+6)=3/4 → x=6. A\'s age = 5×6=30.' },
      { id: 'rp-l3-7', question: 'A mixture has milk and water in ratio 5:3. If 10 liters of water is added, the ratio becomes 5:4. Find the initial quantity of milk.', options: ['40 L', '45 L', '50 L', '55 L'], correctIndex: 2, explanation: 'Let milk=5x,water=3x. 5x/(3x+10)=5/4 → x=10. Milk = 5×10 = 50 L.' },
      { id: 'rp-l3-8', question: '₹2100 is divided among A, B, C such that A:B=3:4 and B:C=4:5. Find C\'s share.', options: ['₹700', '₹775', '₹825', '₹875'], correctIndex: 3, explanation: 'A:B:C = 3:4:5 (B already matches). Total parts=12, unit=175. C = 5×175 = ₹875.' },
      { id: 'rp-l3-9', question: 'The ratio of boys to girls in a school is 8:5. If there are 156 more boys than girls, find the total number of students.', options: ['624', '650', '676', '702'], correctIndex: 2, explanation: 'Difference = 3x = 156 → x=52. Total = 13x = 676.' },
      { id: 'rp-l3-10', question: 'If x:y = 3:5, find the value of (5x + 2y) / (5x − 2y).', options: ['3', '4', '5', '6'], correctIndex: 2, explanation: 'Let x=3k, y=5k. (15k+10k)/(15k−10k) = 25k/5k = 5.' },
    ],
  },
};
