export const timeSpeedDistanceTopic = {
  slug: 'time-speed-distance',
  title: 'Time, Speed & Distance',
  tagline: "Same direction or opposite? Point or platform? Kavya's train journey shows why the setup matters more than the formula.",
  sections: [
    {
      id: 'story',
      title: 'The Story',
      subsections: [
        {
          id: 'kavyas-journey',
          title: "Kavya's Train Journey",
          type: 'concept',
          videoUrl: '',
          explanation: [
            'Kavya takes a 150 km train journey that takes 3 hours. Her speed is simply distance ÷ time = 50 km/h.',
            "That single relationship — Speed = Distance ÷ Time — is the entire foundation of this topic. Every harder question (two trains, a boat against a current, a train crossing a platform) is just this same formula applied more than once, or applied to a cleverly redefined \"distance\".",
            'One practical habit that saves time: exam questions mix km/h and m/s. To convert km/h → m/s, multiply by 5/18. To convert m/s → km/h, multiply by 18/5.',
          ],
        },
      ],
    },
    {
      id: 'speed-basics',
      title: 'Speed, Distance, Time — The Basics',
      subsections: [
        {
          id: 'speed-conversion',
          title: 'The Core Formula and Unit Conversion',
          type: 'animation',
          animationKey: 'speedBasics',
          videoUrl: '',
          explanation: [
            'Speed = Distance ÷ Time. Rearranged: Distance = Speed × Time, or Time = Distance ÷ Speed — pick whichever form isolates what you\'re solving for.',
            'Always double-check units match before calculating — if speed is in km/h but time is in minutes, convert one of them first.',
          ],
        },
      ],
    },
    {
      id: 'relative-speed',
      title: 'Relative Speed',
      subsections: [
        {
          id: 'same-vs-opposite',
          title: 'Same Direction vs Opposite Direction',
          type: 'animation',
          animationKey: 'relativeSpeed',
          videoUrl: '',
          explanation: [
            "When two objects move in the SAME direction, their relative speed (how fast the gap between them changes) is the DIFFERENCE of their speeds — because the faster one is only pulling ahead by that much extra each hour.",
            "When they move in OPPOSITE directions (towards or away from each other), their relative speed is the SUM of their speeds — because they're closing (or opening) the gap from both sides at once.",
            "Same direction → subtract. Opposite direction → add. This one rule covers meeting problems, overtaking problems, and two-train-crossing problems.",
          ],
        },
      ],
    },
    {
      id: 'trains-crossing',
      title: 'Trains Crossing Objects',
      subsections: [
        {
          id: 'train-crossing-distance',
          title: "What 'Distance' Means When a Train Crosses Something",
          type: 'animation',
          animationKey: 'trainCrossing',
          videoUrl: '',
          explanation: [
            'When a train crosses a POINT object (a pole, a standing person) — the distance it needs to cover is just its OWN LENGTH, because the object has no width to add.',
            'When a train crosses a PLATFORM (or another stationary train) — the distance is the train\'s length PLUS the platform\'s length, because the train isn\'t "done crossing" until its tail end clears the far end of the platform.',
            'This redefinition of "distance" is the entire trick to this pattern — the speed formula itself never changes.',
          ],
        },
      ],
    },
    {
      id: 'boats-streams',
      title: 'Boats and Streams',
      subsections: [
        {
          id: 'upstream-downstream',
          title: 'Rowing With or Against the Current',
          type: 'concept',
          videoUrl: '',
          explanation: [
            "A boat's own speed (in still water) either gets HELPED or HINDERED by the current, depending on direction — this is really just relative speed again, with the \"current\" playing the role of a second moving object.",
            'DOWNSTREAM (with the current): effective speed = boat speed + current speed.',
            'UPSTREAM (against the current): effective speed = boat speed − current speed.',
            'Two useful reverses: Boat speed (still water) = (downstream + upstream) ÷ 2. Current speed = (downstream − upstream) ÷ 2.',
          ],
        },
      ],
    },
  ],
  practiceQuestions: [
    {
      id: 'qc1',
      question: 'A car travels 180 km in 3 hours. Find its speed.',
      options: ['50 km/h', '55 km/h', '60 km/h', '65 km/h'],
      correctIndex: 2,
      explanation: 'Speed = 180 ÷ 3 = 60 km/h.',
    },
    {
      id: 'qc2',
      question: 'Convert 36 km/h to m/s.',
      options: ['8 m/s', '9 m/s', '10 m/s', '12 m/s'],
      correctIndex: 2,
      explanation: '36 × 5/18 = 10 m/s.',
    },
    {
      id: 'qc3',
      question: 'Two trains move in the same direction at 60 km/h and 40 km/h. Find their relative speed.',
      options: ['15 km/h', '20 km/h', '25 km/h', '100 km/h'],
      correctIndex: 1,
      explanation: 'Same direction → subtract: 60 − 40 = 20 km/h.',
    },
    {
      id: 'qc4',
      question: 'A train 150m long crosses a pole in 10 seconds. Find its speed.',
      options: ['12 m/s', '13.5 m/s', '15 m/s', '18 m/s'],
      correctIndex: 2,
      explanation: 'Speed = 150 ÷ 10 = 15 m/s.',
    },
    {
      id: 'qc5',
      question: 'A man rows at 6 km/h in still water. Current speed is 2 km/h. Find his downstream speed.',
      options: ['4 km/h', '6 km/h', '8 km/h', '10 km/h'],
      correctIndex: 2,
      explanation: 'Downstream = 6 + 2 = 8 km/h.',
    },
  ],
  practiceBank: {
    level1: [
      { id: 'ts-l1-1', question: 'A car travels 180 km in 3 hours. Find its speed.', options: ['50 km/h', '55 km/h', '60 km/h', '65 km/h'], correctIndex: 2, explanation: '180 ÷ 3 = 60 km/h.' },
      { id: 'ts-l1-2', question: 'A man walks at 5 km/h. How far does he walk in 4 hours?', options: ['15 km', '18 km', '20 km', '22 km'], correctIndex: 2, explanation: '5 × 4 = 20 km.' },
      { id: 'ts-l1-3', question: 'A cyclist covers 60 km in 4 hours. Find his speed.', options: ['12 km/h', '13 km/h', '15 km/h', '16 km/h'], correctIndex: 2, explanation: '60 ÷ 4 = 15 km/h.' },
      { id: 'ts-l1-4', question: 'Convert 36 km/h to m/s.', options: ['8 m/s', '9 m/s', '10 m/s', '12 m/s'], correctIndex: 2, explanation: '36 × 5/18 = 10 m/s.' },
      { id: 'ts-l1-5', question: 'Convert 20 m/s to km/h.', options: ['65 km/h', '68 km/h', '70 km/h', '72 km/h'], correctIndex: 3, explanation: '20 × 18/5 = 72 km/h.' },
      { id: 'ts-l1-6', question: 'A train travels at 90 km/h. How far does it travel in 30 minutes?', options: ['40 km', '42 km', '45 km', '48 km'], correctIndex: 2, explanation: '90 × 0.5 = 45 km.' },
      { id: 'ts-l1-7', question: 'A car covers 240 km at 60 km/h. Find the time taken.', options: ['3 hr', '3.5 hr', '4 hr', '4.5 hr'], correctIndex: 2, explanation: '240 ÷ 60 = 4 hours.' },
      { id: 'ts-l1-8', question: 'Convert 54 km/h to m/s.', options: ['12 m/s', '13 m/s', '15 m/s', '16 m/s'], correctIndex: 2, explanation: '54 × 5/18 = 15 m/s.' },
      { id: 'ts-l1-9', question: 'A man covers 100 km in 2 hours 30 minutes. Find his speed.', options: ['35 km/h', '38 km/h', '40 km/h', '42 km/h'], correctIndex: 2, explanation: '100 ÷ 2.5 = 40 km/h.' },
      { id: 'ts-l1-10', question: 'A cyclist travels at 18 km/h. Find the distance covered in 20 minutes.', options: ['5 km', '5.5 km', '6 km', '6.5 km'], correctIndex: 2, explanation: '18 × (1/3) = 6 km.' },
      { id: 'ts-l1-11', question: 'Convert 25 m/s to km/h.', options: ['85 km/h', '88 km/h', '90 km/h', '92 km/h'], correctIndex: 2, explanation: '25 × 18/5 = 90 km/h.' },
      { id: 'ts-l1-12', question: 'A train covers 360 km in 4 hours. Find its speed in m/s.', options: ['20 m/s', '22 m/s', '25 m/s', '28 m/s'], correctIndex: 2, explanation: '360÷4=90 km/h = 90×5/18 = 25 m/s.' },
      { id: 'ts-l1-13', question: 'A bus travels at 45 km/h for 40 minutes. Find the distance covered.', options: ['25 km', '28 km', '30 km', '32 km'], correctIndex: 2, explanation: '45 × (2/3) = 30 km.' },
      { id: 'ts-l1-14', question: 'A man covers 15 km in 3 hours. Find his speed.', options: ['4 km/h', '4.5 km/h', '5 km/h', '5.5 km/h'], correctIndex: 2, explanation: '15 ÷ 3 = 5 km/h.' },
      { id: 'ts-l1-15', question: 'A car covers 150 km at 50 km/h. Find the time taken in minutes.', options: ['150 min', '165 min', '180 min', '195 min'], correctIndex: 2, explanation: '150÷50=3 hours = 180 minutes.' },
    ],
    level2: [
      { id: 'ts-l2-1', question: 'Two trains move in the SAME direction at 60 km/h and 40 km/h. Find their relative speed.', options: ['15 km/h', '20 km/h', '25 km/h', '100 km/h'], correctIndex: 1, explanation: 'Same direction → subtract: 60−40=20 km/h.' },
      { id: 'ts-l2-2', question: 'Two trains move in OPPOSITE directions at 60 km/h and 40 km/h. Find their relative speed.', options: ['20 km/h', '80 km/h', '90 km/h', '100 km/h'], correctIndex: 3, explanation: 'Opposite direction → add: 60+40=100 km/h.' },
      { id: 'ts-l2-3', question: 'A train 150m long crosses a pole in 10 seconds. Find its speed.', options: ['12 m/s', '13.5 m/s', '15 m/s', '18 m/s'], correctIndex: 2, explanation: 'Speed = 150÷10 = 15 m/s.' },
      { id: 'ts-l2-4', question: 'A train 200m long crosses a platform 300m long in 25 seconds. Find its speed.', options: ['16 m/s', '18 m/s', '20 m/s', '22 m/s'], correctIndex: 2, explanation: 'Distance=200+300=500m. Speed=500÷25=20 m/s.' },
      { id: 'ts-l2-5', question: 'Two trains 100m and 150m long run in opposite directions at 40 km/h and 32 km/h. Find the time to cross each other.', options: ['10 sec', '11.5 sec', '12.5 sec', '14 sec'], correctIndex: 2, explanation: 'Relative speed=72km/h=20m/s. Distance=250m. Time=250÷20=12.5 sec.' },
      { id: 'ts-l2-6', question: 'A man rows at 6 km/h in still water. Current speed is 2 km/h. Find his downstream speed.', options: ['4 km/h', '6 km/h', '8 km/h', '10 km/h'], correctIndex: 2, explanation: 'Downstream=6+2=8 km/h.' },
      { id: 'ts-l2-7', question: 'A man rows at 6 km/h in still water. Current speed is 2 km/h. Find his upstream speed.', options: ['2 km/h', '3 km/h', '4 km/h', '5 km/h'], correctIndex: 2, explanation: 'Upstream=6−2=4 km/h.' },
      { id: 'ts-l2-8', question: "A boat's downstream speed is 15 km/h and upstream is 9 km/h. Find the boat's speed in still water.", options: ['10 km/h', '11 km/h', '12 km/h', '13 km/h'], correctIndex: 2, explanation: '(15+9)/2 = 12 km/h.' },
      { id: 'ts-l2-9', question: "A boat's downstream speed is 15 km/h and upstream is 9 km/h. Find the speed of the current.", options: ['2 km/h', '3 km/h', '4 km/h', '5 km/h'], correctIndex: 1, explanation: '(15−9)/2 = 3 km/h.' },
      { id: 'ts-l2-10', question: 'A train 120m long runs at 60 km/h. Find the time it takes to cross a man standing on the platform.', options: ['6.2 sec', '6.8 sec', '7.2 sec', '7.8 sec'], correctIndex: 2, explanation: 'Speed=60km/h≈16.67m/s. Time=120÷16.67≈7.2 sec.' },
      { id: 'ts-l2-11', question: 'Two cars start from the same point, same time, in the same direction at 50 km/h and 65 km/h. Find the distance between them after 3 hours.', options: ['35 km', '40 km', '45 km', '50 km'], correctIndex: 2, explanation: 'Relative speed=15km/h. Distance in 3hr=45km.' },
      { id: 'ts-l2-12', question: 'Two men walk towards each other from points 60 km apart, at 8 km/h and 12 km/h. Find the time to meet.', options: ['2 hr', '2.5 hr', '3 hr', '3.5 hr'], correctIndex: 2, explanation: 'Relative speed=20km/h. Time=60÷20=3 hours.' },
      { id: 'ts-l2-13', question: 'A train travels 300 km at 60 km/h and returns at 50 km/h. Find the total time for the round trip.', options: ['9 hr', '10 hr', '11 hr', '12 hr'], correctIndex: 2, explanation: 'Time1=5hr, Time2=6hr. Total=11 hours.' },
      { id: 'ts-l2-14', question: 'A car covers a distance in 5 hours at 40 km/h. Find the speed required to cover the same distance in 4 hours.', options: ['45 km/h', '48 km/h', '50 km/h', '52 km/h'], correctIndex: 2, explanation: 'Distance=200km. Speed=200÷4=50 km/h.' },
      { id: 'ts-l2-15', question: 'A train crosses a 250m platform in 20 sec and a pole in 10 sec. Find the length of the train.', options: ['200 m', '225 m', '250 m', '275 m'], correctIndex: 2, explanation: 'Using L=10v and L+250=20v, solving gives L=250m.' },
    ],
    level3: [
      { id: 'ts-l3-1', question: 'Two trains, 120m and 180m long, run in the SAME direction at 60 km/h and 42 km/h. Find the time to cross each other.', options: ['48 sec', '54 sec', '60 sec', '66 sec'], correctIndex: 2, explanation: 'Relative speed=18km/h=5m/s. Distance=300m. Time=300÷5=60 sec.' },
      { id: 'ts-l3-2', question: 'A boat covers 24 km upstream in 6 hours and returns downstream in 4 hours. Find the boat\'s speed in still water.', options: ['4 km/h', '4.5 km/h', '5 km/h', '5.5 km/h'], correctIndex: 2, explanation: 'Upstream=4km/h, downstream=6km/h. Boat speed=(4+6)/2=5 km/h.' },
      { id: 'ts-l3-3', question: 'A train at 72 km/h crosses a platform in 30 sec and a man standing on it in 18 sec. Find the platform\'s length.', options: ['220 m', '230 m', '240 m', '250 m'], correctIndex: 2, explanation: 'Speed=20m/s. Train length=20×18=360m. Total crossing=20×30=600m. Platform=600−360=240m.' },
      { id: 'ts-l3-4', question: 'Stations A and B are 420 km apart. Trains start from each at 9:00 AM, at 60 km/h and 80 km/h, moving towards each other. When do they meet?', options: ['11:30 AM', '12:00 PM', '12:30 PM', '1:00 PM'], correctIndex: 1, explanation: 'Relative speed=140km/h. Time=420÷140=3 hours. 9:00 AM + 3hr = 12:00 PM.' },
      { id: 'ts-l3-5', question: 'A man rows 30 km downstream in 2 hours and returns upstream in 5 hours. Find the boat\'s speed in still water.', options: ['9.5 km/h', '10 km/h', '10.5 km/h', '11 km/h'], correctIndex: 2, explanation: 'Downstream=15km/h, upstream=6km/h. Boat speed=(15+6)/2=10.5 km/h.' },
      { id: 'ts-l3-6', question: 'A thief is spotted 200m away by a policeman. Thief runs at 10 km/h, policeman chases at 12 km/h. Find the distance the thief runs before being caught.', options: ['800 m', '900 m', '1000 m', '1100 m'], correctIndex: 2, explanation: 'Relative speed=2km/h. Time to close 200m=0.1hr. Thief\'s distance=10×0.1=1km=1000m.' },
      { id: 'ts-l3-7', question: 'A 240m train crosses a 260m train (opposite direction) in 12 sec. If the first train\'s speed is 45 km/h, find the second train\'s speed.', options: ['95 km/h', '100 km/h', '105 km/h', '110 km/h'], correctIndex: 2, explanation: 'Distance=500m. Relative speed=500/12 m/s≈150km/h. Second train=150−45=105 km/h.' },
      { id: 'ts-l3-8', question: 'A boat goes 24 km upstream and 24 km downstream in a total of 5 hours. If the boat\'s speed in still water is 10 km/h, find the current\'s speed.', options: ['1.5 km/h', '2 km/h', '2.5 km/h', '3 km/h'], correctIndex: 1, explanation: 'Solving 24/(10−c)+24/(10+c)=5 gives c=2 km/h.' },
      { id: 'ts-l3-9', question: 'A car travels from X to Y at 60 km/h and returns at 40 km/h. Total time taken is 5 hours. Find the distance between X and Y.', options: ['100 km', '110 km', '120 km', '130 km'], correctIndex: 2, explanation: 'd/60+d/40=5 → 5d/120=5 → d=120 km.' },
      { id: 'ts-l3-10', question: 'Excluding stoppages, a train travels at 60 km/h; including stoppages, at 45 km/h. Find the stoppage time per hour.', options: ['10 min', '12 min', '15 min', '18 min'], correctIndex: 2, explanation: 'Moving time for 45km at 60km/h = 45min. Stoppage = 60−45 = 15 min per hour.' },
    ],
  },
};
