export const timeWorkTopic = {
  slug: 'time-and-work',
  title: 'Time & Work',
  tagline: 'Why do we divide 1 by the number of days? Follow Ravi and Kumar painting a wall to see the logic, not just the formula.',
  sections: [
    {
      id: 'story',
      title: 'The Story',
      subsections: [
        {
          id: 'the-wall',
          title: 'Ravi and Kumar Paint a Wall',
          type: 'concept',
          videoUrl: '',
          explanation: [
            'Ravi can paint a wall alone in 6 days. Kumar can paint the same wall alone in 8 days.',
            'Question: if Ravi and Kumar paint the wall TOGETHER, how many days will it take?',
            "You can't just average 6 and 8, and you can't just add them either — working together isn't that simple. To solve this properly, we need a way to measure how much of the wall each person paints in ONE day. That single idea — a common unit of \"how much work gets done per day\" — is the key to every Time & Work problem.",
          ],
        },
      ],
    },
    {
      id: 'efficiency',
      title: "One Person's Efficiency",
      subsections: [
        {
          id: 'one-day-work',
          title: "What does '1 day's work' mean?",
          type: 'animation',
          animationKey: 'workerEfficiency',
          videoUrl: '',
          explanation: [
            'If Ravi finishes the WHOLE wall in 6 days, and he works at a steady pace every day, then in 1 day he must finish exactly 1/6th of the wall.',
            "This fraction — 1/6 — is called Ravi's EFFICIENCY, or his rate of work. It answers the question \"how much does he complete in one day?\"",
            'This is the trick that makes the whole topic work: instead of thinking in "days to finish", we flip it around and think in "fraction finished per day". Fractions can be added together — days alone can\'t.',
          ],
        },
      ],
    },
    {
      id: 'combined',
      title: 'Working Together',
      subsections: [
        {
          id: 'combined-efficiency',
          title: 'Adding Their Efficiencies',
          type: 'animation',
          animationKey: 'combinedWork',
          videoUrl: '',
          explanation: [
            "Ravi's rate is 1/6 per day. Kumar's rate is 1/8 per day. Since they're painting the SAME wall at the SAME time, their daily progress simply adds up.",
            'Combined rate = 1/6 + 1/8. To add these, convert to a common denominator (24): 4/24 + 3/24 = 7/24. So together, they finish 7/24 of the wall every day.',
            'If 7/24 gets done in 1 day, the whole wall (24/24) takes 24 ÷ 7 days — about 3.43 days. That\'s faster than Ravi alone (6 days) and faster than Kumar alone (8 days), which makes sense — two people working together should finish quicker.',
          ],
        },
      ],
    },
    {
      id: 'lcm-shortcut',
      title: 'The Fast Way — LCM Method',
      subsections: [
        {
          id: 'lcm-shortcut-method',
          title: 'Skip the Fractions Using LCM',
          type: 'animation',
          animationKey: 'lcmShortcutWork',
          videoUrl: '',
          explanation: [
            "Fractions are correct but slow to work with under exam time pressure. Here's the shortcut every fast solver uses: instead of treating the wall as \"1 whole job\", assume the total work is LCM(6, 8) = 24 \"units\" — remember LCM from the last topic? This is exactly where it's used in practice.",
            "Why 24 specifically? Because 24 divides evenly by both 6 and 8, so BOTH workers' daily output becomes a whole number instead of a fraction.",
            "Ravi's efficiency = 24 units ÷ 6 days = 4 units/day. Kumar's efficiency = 24 units ÷ 8 days = 3 units/day. Combined = 4 + 3 = 7 units/day.",
            'Days to finish = 24 units ÷ 7 units/day = 24/7 days — the exact same answer as the fraction method, just reached with whole numbers, which is much faster to compute mentally.',
          ],
        },
      ],
    },
    {
      id: 'wages',
      title: 'Extension: Work and Wages',
      subsections: [
        {
          id: 'work-and-wages',
          title: 'Splitting Payment by Work Done',
          type: 'concept',
          videoUrl: '',
          explanation: [
            "If Ravi and Kumar are paid together for painting the wall, the payment should be split in the same ratio as the work each of them actually did — NOT split equally, since they didn't do equal work.",
            "Using the LCM method: Ravi did 4 units/day and Kumar did 3 units/day, working the same number of days together. So their total work ratio is 4 : 3, and that's exactly how the wages should be split.",
            '(Full animated walkthrough for this extension coming in a future update.)',
          ],
        },
      ],
    },
  ],
  practiceQuestions: [
    {
      id: 'q1',
      question: 'Ravi finishes a job in 6 days, Kumar in 8 days. Working together, how many days will they take?',
      options: ['7 days', '24/7 days', '14 days', '3 days'],
      correctIndex: 1,
      explanation: 'Combined rate = 1/6 + 1/8 = 7/24 per day, so time = 24/7 days ≈ 3.43 days.',
    },
    {
      id: 'q2',
      question: "Using the LCM method with total work = 24 units, what is Ravi's efficiency (Ravi takes 6 days alone)?",
      options: ['3 units/day', '4 units/day', '6 units/day', '8 units/day'],
      correctIndex: 1,
      explanation: 'Efficiency = total units ÷ days = 24 ÷ 6 = 4 units/day.',
    },
    {
      id: 'q3',
      question: "Ravi does 1/6 of a job per day. How many days does he need to finish HALF the job alone?",
      options: ['2 days', '3 days', '4 days', '6 days'],
      correctIndex: 1,
      explanation: 'Half the job = 1/2. Days = (1/2) ÷ (1/6) = 3 days.',
    },
    {
      id: 'q4',
      question: 'A and B together finish a job in 4 days. A alone takes 12 days. How many days does B alone take?',
      options: ['3 days', '6 days', '8 days', '16 days'],
      correctIndex: 1,
      explanation: '1/A + 1/B = 1/4. 1/12 + 1/B = 1/4, so 1/B = 1/4 − 1/12 = 1/6, meaning B takes 6 days.',
    },
    {
      id: 'q5',
      question: 'A does twice as much work as B on the same job. In what ratio should their wages be split?',
      options: ['1 : 1', '1 : 2', '2 : 1', '3 : 1'],
      correctIndex: 2,
      explanation: 'Wages split in the ratio of work actually done — A did twice as much, so the ratio is 2 : 1.',
    },
  ],
  practiceBank: {
    level1: [
      { id: 'tw-l1-1', question: "A can complete a job in 10 days. What is A's one day's work?", options: ['1/8', '1/9', '1/10', '1/12'], correctIndex: 2, explanation: 'One day\'s work = 1 ÷ days = 1/10.' },
      { id: 'tw-l1-2', question: 'B can complete a work in 15 days. What fraction of the work does B do in 5 days?', options: ['1/5', '1/4', '1/3', '2/5'], correctIndex: 2, explanation: '5/15 = 1/3.' },
      { id: 'tw-l1-3', question: "If A does 1/8 of a work in one day, in how many days will A finish the whole work?", options: ['6', '7', '8', '9'], correctIndex: 2, explanation: 'Days = 1 ÷ (1/8) = 8.' },
      { id: 'tw-l1-4', question: 'A can finish a piece of work in 20 days. In how many days will A finish 3/5 of the work?', options: ['10', '12', '14', '15'], correctIndex: 1, explanation: '3/5 × 20 = 12 days.' },
      { id: 'tw-l1-5', question: "A works at 1/6 per day and B works at 1/9 per day. Find their combined one day's work.", options: ['5/18', '1/15', '2/15', '7/18'], correctIndex: 0, explanation: '1/6 + 1/9 = 3/18 + 2/18 = 5/18.' },
      { id: 'tw-l1-6', question: 'A can do a job in 12 days, B in 24 days. What fraction of the job do they complete together in 1 day?', options: ['1/6', '1/8', '1/12', '1/16'], correctIndex: 1, explanation: '1/12 + 1/24 = 2/24 + 1/24 = 3/24 = 1/8.' },
      { id: 'tw-l1-7', question: 'A can complete a task in 9 days. How much work does A complete in 3 days?', options: ['1/2', '1/3', '2/3', '1/4'], correctIndex: 1, explanation: '3/9 = 1/3.' },
      { id: 'tw-l1-8', question: 'A job takes 18 days for one person alone. After working 6 days, what fraction of the work remains?', options: ['1/3', '2/3', '1/2', '3/4'], correctIndex: 1, explanation: 'Done = 6/18 = 1/3. Remaining = 2/3.' },
      { id: 'tw-l1-9', question: 'A can do a piece of work in 6 days and B can do it in 12 days. Working together, how many days will they take?', options: ['3', '4', '5', '6'], correctIndex: 1, explanation: '1/6+1/12 = 3/12 = 1/4 → 4 days.' },
      { id: 'tw-l1-10', question: 'A can finish a work in 25 days. What percentage of the work does A complete in 10 days?', options: ['30%', '35%', '40%', '45%'], correctIndex: 2, explanation: '10/25 = 0.40 = 40%.' },
      { id: 'tw-l1-11', question: 'A and B can each individually finish a job in 8 days. Working together, how many days will they take?', options: ['2', '3', '4', '5'], correctIndex: 2, explanation: '1/8+1/8 = 1/4 → 4 days.' },
      { id: 'tw-l1-12', question: 'A can do a job in 15 days. B is twice as efficient as A. In how many days can B alone do the job?', options: ['5', '6', '7.5', '10'], correctIndex: 2, explanation: "B's rate = 2×(1/15). B's days = 15/2 = 7.5." },
      { id: 'tw-l1-13', question: 'A can complete a work in 10 days and is thrice as efficient as B. In how many days can B alone complete it?', options: ['20', '25', '30', '35'], correctIndex: 2, explanation: "B's rate = (1/10)/3 = 1/30 → 30 days." },
      { id: 'tw-l1-14', question: 'A can complete a work in 40 days. How many days will A take to complete half the work?', options: ['15', '18', '20', '22'], correctIndex: 2, explanation: 'Half of 40 = 20 days.' },
      { id: 'tw-l1-15', question: 'A and B together can complete a work in 6 days. A alone can do it in 10 days. In how many days can B alone do it?', options: ['12', '15', '18', '20'], correctIndex: 1, explanation: '1/6 − 1/10 = 5/30 − 3/30 = 2/30 = 1/15 → 15 days.' },
    ],
    level2: [
      { id: 'tw-l2-1', question: 'A can do a work in 12 days and B in 15 days. They work together for 4 days, then A leaves. How many more days will B take to finish?', options: ['4', '5', '6', '7'], correctIndex: 2, explanation: 'Done in 4 days = 4×(1/12+1/15) = 4×9/60 = 0.6. Remaining 0.4 ÷ (1/15) = 6 days.' },
      { id: 'tw-l2-2', question: 'A, B, and C can complete a work in 10, 15, and 30 days respectively. Working together, how many days will they take?', options: ['4', '5', '6', '7'], correctIndex: 1, explanation: '1/10+1/15+1/30 = 3/30+2/30+1/30 = 6/30 = 1/5 → 5 days.' },
      { id: 'tw-l2-3', question: 'A is twice as efficient as B, and together they finish a work in 12 days. In how many days can A alone finish it?', options: ['16', '18', '20', '24'], correctIndex: 1, explanation: 'B rate=x, A rate=2x. 3x=1/12 → x=1/36. A rate=2/36=1/18 → 18 days.' },
      { id: 'tw-l2-4', question: 'A can do a work in 20 days. He works for 5 days, then B finishes the rest in 15 days. In how many days can B alone finish the whole work?', options: ['18', '20', '22', '24'], correctIndex: 1, explanation: 'A did 5/20=1/4. Remaining 3/4 in 15 days → B rate = (3/4)/15 = 1/20 → 20 days.' },
      { id: 'tw-l2-5', question: 'A and B can do a job together in 8 days. A alone can do it in 12 days. How long will B alone take?', options: ['20', '22', '24', '26'], correctIndex: 2, explanation: '1/8−1/12 = 3/24−2/24 = 1/24 → 24 days.' },
      { id: 'tw-l2-6', question: 'A can do a work alone in 6 days and B in 9 days. If total wages are ₹900, what is A\'s share when they work together?', options: ['₹450', '₹500', '₹540', '₹600'], correctIndex: 2, explanation: 'Rate ratio A:B = 1/6:1/9 = 3:2. A\'s share = 900×(3/5) = 540.' },
      { id: 'tw-l2-7', question: 'A can complete a work in 18 days. With B\'s help, they complete it in 12 days. In how many days can B alone complete it?', options: ['30', '33', '36', '40'], correctIndex: 2, explanation: '1/12−1/18 = 3/36−2/36 = 1/36 → 36 days.' },
      { id: 'tw-l2-8', question: 'Twelve men can complete a work in 8 days. How many days will 6 men take to complete the same work?', options: ['12', '14', '16', '18'], correctIndex: 2, explanation: 'Total man-days = 96. 96÷6 = 16 days.' },
      { id: 'tw-l2-9', question: '15 workers can build a wall in 20 days. How many workers are needed to build it in 12 days?', options: ['20', '22', '25', '28'], correctIndex: 2, explanation: 'Total work = 300 worker-days. 300÷12 = 25 workers.' },
      { id: 'tw-l2-10', question: 'A can do a work in 24 days, B in 32 days. They start together, but A leaves 4 days before completion. Find the total days taken.', options: ['14', '15', '16', '18'], correctIndex: 2, explanation: '(D−4)/24 + D/32 = 1 → 4(D−4)+3D=96 → 7D=112 → D=16.' },
      { id: 'tw-l2-11', question: 'A and B can do a work in 10 days, B and C in 12 days, C and A in 15 days. In how many days can A, B, and C together complete it?', options: ['6', '7', '8', '9'], correctIndex: 2, explanation: 'Sum of pairwise rates = 1/10+1/12+1/15 = 15/60 = 1/4 = 2(A+B+C) → A+B+C=1/8 → 8 days.' },
      { id: 'tw-l2-12', question: 'A can do a job in 6 days working 8 hours a day. How many days will he take working 6 hours a day?', options: ['6', '7', '8', '9'], correctIndex: 2, explanation: 'Total hours = 48. 48÷6 = 8 days.' },
      { id: 'tw-l2-13', question: 'A can do a work in 12 days. He works alone for 3 days, then B joins and together they finish the remaining work in 6 days. In how many days can B alone complete it?', options: ['18', '20', '22', '24'], correctIndex: 3, explanation: 'A did 3/12=1/4. Remaining 3/4 in 6 days → combined rate 1/8. B rate = 1/8−1/12 = 1/24 → 24 days.' },
      { id: 'tw-l2-14', question: 'A is 50% more efficient than B. If B can complete a work in 18 days, in how many days can A complete it?', options: ['10', '12', '14', '15'], correctIndex: 1, explanation: 'A rate = 1.5×(1/18) = 1/12 → 12 days.' },
      { id: 'tw-l2-15', question: 'Two pipes can fill a tank in 10 and 15 minutes respectively. If both are opened together, how long will the tank take to fill?', options: ['5 min', '6 min', '7 min', '8 min'], correctIndex: 1, explanation: '1/10+1/15 = 3/30+2/30 = 1/6 → 6 minutes.' },
    ],
    level3: [
      { id: 'tw-l3-1', question: 'A, B, and C can complete a work in 10, 12, and 15 days respectively. They start together, but A leaves 5 days before completion. In how many days is the work completed?', options: ['5', '6', '7', '8'], correctIndex: 1, explanation: '(D−5)/10 + D/12 + D/15 = 1 → 6(D−5)+5D+4D=60 → 15D−30=60 → D=6.' },
      { id: 'tw-l3-2', question: 'A can complete a work in 15 days and B in 10 days. They work on alternate days, starting with A. In how many days is the work completed?', options: ['10', '11', '12', '13'], correctIndex: 2, explanation: 'Each A+B pair of days does 1/15+1/10 = 1/6 of the work. 6 pairs = 12 days finishes exactly 1 whole work.' },
      { id: 'tw-l3-3', question: 'Taps A and B fill a tank in 12 and 15 minutes; tap C drains it in 20 minutes. If all three are opened together, how long will the tank take to fill?', options: ['8 min', '10 min', '12 min', '15 min'], correctIndex: 1, explanation: '1/12+1/15−1/20 = 5/60+4/60−3/60 = 6/60 = 1/10 → 10 minutes.' },
      { id: 'tw-l3-4', question: 'A does 3/4 of a work in 15 days, then B finishes the remaining work in 5 days. If A and B work together from the start, how many days will they take?', options: ['8', '9', '10', '12'], correctIndex: 2, explanation: 'A rate = (3/4)/15 = 1/20. B rate = (1/4)/5 = 1/20. Combined = 1/10 → 10 days.' },
      { id: 'tw-l3-5', question: 'A can complete a work in 18 days. B is 50% less efficient than A. Working together, how many days will they take?', options: ['10', '11', '12', '14'], correctIndex: 2, explanation: 'B rate = 0.5×(1/18) = 1/36. Combined = 1/18+1/36 = 3/36 = 1/12 → 12 days.' },
      { id: 'tw-l3-6', question: 'A, B, and C together complete a work in 6 days. A alone can do it in 18 days, B alone in 24 days. In how many days can C alone complete it?', options: ['13.5 days', '14.4 days', '15.2 days', '16 days'], correctIndex: 1, explanation: 'A+B = 1/18+1/24 = 7/72. C = 1/6−7/72 = 5/72 → 72/5 = 14.4 days.' },
      { id: 'tw-l3-7', question: 'A and B undertake a job for ₹720. A alone can do it in 6 days, B in 8 days. With C\'s help they finish in 3 days. Find C\'s share of the wages.', options: ['₹60', '₹75', '₹90', '₹105'], correctIndex: 2, explanation: 'A+B rate=7/24. C rate=1/3−7/24=1/24. Ratio A:B:C=4:3:1 → C\'s share = 720×(1/8) = 90.' },
      { id: 'tw-l3-8', question: 'A can complete a work in x days and B in (x+6) days. Together they complete it in 4 days. Find x.', options: ['4', '5', '6', '7'], correctIndex: 2, explanation: '1/x+1/(x+6)=1/4 leads to x²−2x−24=0 → (x−6)(x+4)=0 → x=6.' },
      { id: 'tw-l3-9', question: 'A tank is filled by pipe A in 6 hours and emptied by pipe B in 8 hours. If both are opened together, how long will the tank take to fill?', options: ['20 hrs', '22 hrs', '24 hrs', '26 hrs'], correctIndex: 2, explanation: 'Net rate = 1/6−1/8 = 4/24−3/24 = 1/24 → 24 hours.' },
      { id: 'tw-l3-10', question: 'A completes a work in 15 days working 6 hours/day; B completes the same work in 10 days working 9 hours/day. If both work together 5 hours/day, in how many days will they finish?', options: ['7', '8', '9', '10'], correctIndex: 2, explanation: "Both A and B's total work-hours = 90. Combined rate = 2/90 per hour. At 5 hrs/day: 5/45=1/9 per day → 9 days." },
    ],
  },
};
