// server/scripts/buildAptitude.mjs
//
// Merges the raw chunk files that content-generation agents write into the
// final per-topic JSON that seedAptitude.js loads, and validates everything.
//
//   content/aptitude/_taxonomy.json              <- topic list + quotas (source of truth)
//   content/aptitude/_chunks/<slug>/*.json       <- agent output (one file per sub-pattern)
//   content/aptitude/<slug>.json                 <- GENERATED by this script
//
// Usage (from server/):
//   node scripts/buildAptitude.mjs <slug>        build + validate one topic
//   node scripts/buildAptitude.mjs --all         build every topic that has chunks
//   node scripts/buildAptitude.mjs --check       validate only, write nothing
//   node scripts/buildAptitude.mjs --report      coverage table for all topics
//
// What it does for the agents so they don't have to:
//   * assigns `order` numbers
//   * shuffles option positions so correct answers are evenly spread over
//     A/B/C/D (LLM-written MCQs are heavily skewed to one position otherwise)
//     — questions whose options contain "All of the above"/"None of these"
//     style choices keep their order.
//
// Exit code is non-zero if any topic has ERRORS (warnings do not fail).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(__dirname, '..', 'content', 'aptitude');
const CHUNKS = path.join(DIR, '_chunks');
const taxonomy = JSON.parse(fs.readFileSync(path.join(DIR, '_taxonomy.json'), 'utf8'));

const DIFFS = ['easy', 'medium', 'hard'];
const EXAM_STYLES = ['campus-it', 'banking', 'ssc', 'cat-style', 'general'];
const SET_TYPES = ['text', 'table', 'bar', 'line', 'pie'];
const FIXED_ORDER_RE = /^(all of (the|these)|none of (the|these)|both|neither|any of|cannot be determined|data (is )?(inadequate|insufficient)|more than one)/i;
const OPTION_REF_RE = /\b(option|choice)\s*\(?[a-d1-4]\)?\b|\(\s*[a-d]\s*\)\s*(is|and|or)\b/i;
const NEEDS_SET_RE = /\b(the|following|given|above)\s+(table|chart|graph|pie|passage|paragraph|data|figure|diagram|arrangement|information|caselet)\b/i;

// Small seeded PRNG so rebuilding is reproducible (no noisy git diffs).
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function hash(str) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
  return h >>> 0;
}
function shuffle(arr, rnd) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function readChunks(slug) {
  const dir = path.join(CHUNKS, slug);
  if (!fs.existsSync(dir)) return null;
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
  const errors = [];
  const questions = [];
  const sets = [];
  for (const f of files) {
    let raw;
    try { raw = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); }
    catch (e) { errors.push(`${f}: invalid JSON (${e.message})`); continue; }
    const qs = Array.isArray(raw) ? raw : raw.questions;
    if (!Array.isArray(qs)) { errors.push(`${f}: needs a "questions" array`); continue; }
    if (!Array.isArray(raw)) for (const s of raw.sets || []) sets.push({ ...s, _file: f });
    qs.forEach((q, i) => questions.push({ ...q, _file: f, _idx: i + 1 }));
  }
  return { files, questions, sets, errors };
}

function validateSet(s, errors) {
  const w = `set "${s.id}" (${s._file})`;
  if (!s.id || typeof s.id !== 'string') return errors.push(`${s._file}: a set is missing "id"`);
  if (!SET_TYPES.includes(s.type)) errors.push(`${w}: type must be one of ${SET_TYPES.join('/')}`);
  if (s.type === 'text' && !(typeof s.text === 'string' && s.text.trim().length >= 40)) errors.push(`${w}: text sets need "text" (>= 40 chars)`);
  if (s.type === 'table') {
    const t = s.table;
    if (!t || !Array.isArray(t.columns) || !Array.isArray(t.rows) || t.rows.length < 2) errors.push(`${w}: table needs {columns:[], rows:[[],...]} with >= 2 rows`);
    else if (t.rows.some((r) => !Array.isArray(r) || r.length !== t.columns.length)) errors.push(`${w}: every table row must have ${t.columns.length} cells`);
  }
  if (['bar', 'line', 'pie'].includes(s.type)) {
    const c = s.chart;
    if (!c || !Array.isArray(c.series) || c.series.length === 0) errors.push(`${w}: chart needs {series:[{name,data:[{label,value}]}]}`);
    else {
      for (const se of c.series) {
        if (!se.name || !Array.isArray(se.data) || se.data.length < 2 || se.data.some((d) => d.label === undefined || typeof d.value !== 'number'))
          errors.push(`${w}: each series needs name + data[{label, value:number}] (>= 2 points)`);
      }
      if (s.type === 'pie' && c.series.length === 1) {
        const total = c.series[0].data.reduce((a, d) => a + (d.value || 0), 0);
        if (Math.abs(total - 100) > 0.5 && Math.abs(total - 360) > 0.5) errors.push(`${w}: pie values must sum to 100 (percent) or 360 (degrees), got ${total}`);
      }
    }
  }
}

function buildTopic(topic, { write }) {
  const errors = [];
  const warnings = [];
  const data = readChunks(topic.slug);
  if (!data) return { topic, skipped: true, errors, warnings };
  errors.push(...data.errors);

  const subSlugs = new Set(topic.subPatterns.map((s) => s.slug));
  const subOrder = new Map(topic.subPatterns.map((s, i) => [s.slug, i]));

  // sets
  const setIds = new Map();
  for (const s of data.sets) {
    validateSet(s, errors);
    if (setIds.has(s.id)) errors.push(`duplicate set id "${s.id}"`);
    setIds.set(s.id, { ...s, questionCount: 0 });
  }

  // questions
  const seenText = new Map();
  const cleaned = [];
  for (const q of data.questions) {
    const w = `${q._file} #${q._idx}`;
    const text = String(q.questionText || '').trim();
    if (text.length < 10) { errors.push(`${w}: questionText too short`); continue; }
    if (!Array.isArray(q.options) || q.options.length !== 4) { errors.push(`${w}: needs exactly 4 options`); continue; }
    const opts = q.options.map((o) => String(typeof o === 'string' ? o : o?.text ?? '').trim());
    if (opts.some((o) => !o)) { errors.push(`${w}: empty option`); continue; }
    if (new Set(opts.map((o) => o.toLowerCase())).size !== 4) errors.push(`${w}: duplicate options`);
    if (!Number.isInteger(q.correctOptionIndex) || q.correctOptionIndex < 0 || q.correctOptionIndex > 3) { errors.push(`${w}: correctOptionIndex must be 0-3`); continue; }
    const expl = String(q.explanation || '').trim();
    if (expl.length < 25) errors.push(`${w}: explanation too short (need a worked solution)`);
    if (OPTION_REF_RE.test(expl) || OPTION_REF_RE.test(text)) errors.push(`${w}: do not refer to option letters/numbers — options get shuffled`);
    if (!subSlugs.has(q.subPattern)) errors.push(`${w}: subPattern "${q.subPattern}" not in taxonomy (${[...subSlugs].join(', ')})`);
    if (!DIFFS.includes(q.difficulty)) errors.push(`${w}: difficulty must be easy|medium|hard`);
    const styles = q.examStyles ?? ['general'];
    if (!Array.isArray(styles) || styles.some((x) => !EXAM_STYLES.includes(x))) errors.push(`${w}: examStyles must be from ${EXAM_STYLES.join('|')}`);
    if (q.setId) {
      if (!setIds.has(q.setId)) errors.push(`${w}: setId "${q.setId}" not defined`);
      else setIds.get(q.setId).questionCount += 1;
    } else {
      if (topic.setsRequired) errors.push(`${w}: this topic requires every question to belong to a set (setId)`);
      else if (topic.category !== 'Verbal Ability' && NEEDS_SET_RE.test(text)) errors.push(`${w}: refers to a table/chart/passage/data but has no setId — the learner would see nothing to look at`);
    }
    const key = text.toLowerCase().replace(/\s+/g, ' ');
    if (seenText.has(key)) errors.push(`${w}: duplicate of ${seenText.get(key)}`); else seenText.set(key, w);
    cleaned.push({
      questionText: text, opts, correct: q.correctOptionIndex, explanation: expl,
      shortcut: String(q.shortcut || '').trim(), subPattern: q.subPattern, difficulty: q.difficulty,
      examStyles: styles, setId: q.setId || undefined, tags: Array.isArray(q.tags) ? q.tags : [],
    });
  }

  for (const s of setIds.values()) {
    if (s.questionCount === 0) warnings.push(`set "${s.id}" has no questions`);
    else if (s.questionCount < 2 && s.type !== 'text') warnings.push(`set "${s.id}" has only ${s.questionCount} question (aim for 3-5)`);
  }

  // coverage
  const bySub = new Map(topic.subPatterns.map((s) => [s.slug, 0]));
  const byDiff = { easy: 0, medium: 0, hard: 0 };
  for (const q of cleaned) { if (bySub.has(q.subPattern)) bySub.set(q.subPattern, bySub.get(q.subPattern) + 1); if (byDiff[q.difficulty] !== undefined) byDiff[q.difficulty]++; }
  if (cleaned.length < topic.minQuestions) warnings.push(`only ${cleaned.length}/${topic.minQuestions} questions`);
  for (const [sub, n] of bySub) if (n < topic.minPerSubPattern) warnings.push(`sub-pattern "${sub}" has ${n}/${topic.minPerSubPattern}`);
  const total = cleaned.length || 1;
  const pct = (n) => Math.round((n / total) * 100);
  if (cleaned.length >= 40) {
    if (pct(byDiff.easy) < 20 || pct(byDiff.easy) > 40) warnings.push(`easy is ${pct(byDiff.easy)}% (target ~30%)`);
    if (pct(byDiff.medium) < 40 || pct(byDiff.medium) > 60) warnings.push(`medium is ${pct(byDiff.medium)}% (target ~50%)`);
    if (pct(byDiff.hard) < 10 || pct(byDiff.hard) > 30) warnings.push(`hard is ${pct(byDiff.hard)}% (target ~20%)`);
  }

  // order + balanced answer positions
  cleaned.sort((a, b) => subOrder.get(a.subPattern) - subOrder.get(b.subPattern) || DIFFS.indexOf(a.difficulty) - DIFFS.indexOf(b.difficulty));
  const rnd = mulberry32(hash(topic.slug));
  let bag = [];
  const posCount = [0, 0, 0, 0];
  const questions = cleaned.map((q, i) => {
    const correctText = q.opts[q.correct];
    const fixed = q.opts.some((o) => FIXED_ORDER_RE.test(o));
    let options = q.opts;
    if (!fixed) {
      if (bag.length === 0) bag = shuffle([0, 1, 2, 3], rnd);
      const target = bag.pop();
      const others = shuffle(q.opts.filter((_, idx) => idx !== q.correct), rnd);
      options = [...others.slice(0, target), correctText, ...others.slice(target)];
    }
    const correctOptionIndex = options.indexOf(correctText);
    posCount[correctOptionIndex]++;
    const out = {
      questionText: q.questionText,
      options: options.map((text) => ({ text })),
      correctOptionIndex,
      explanation: q.explanation,
      order: i + 1,
      subPattern: q.subPattern,
      difficulty: q.difficulty,
      examStyles: q.examStyles,
    };
    if (q.shortcut) out.shortcut = q.shortcut;
    if (q.setId) out.setId = q.setId;
    if (q.tags.length) out.tags = q.tags;
    return out;
  });

  if (write && errors.length === 0) {
    const used = new Set(questions.map((q) => q.setId).filter(Boolean));
    const file = {
      pattern: {
        title: topic.title, slug: topic.slug, description: topic.description, order: topic.order,
        passPercentage: topic.passPercentage, timeLimitMinutes: topic.timeLimitMinutes,
        category: topic.category, testQuestionCount: topic.testQuestionCount,
        subPatterns: topic.subPatterns,
      },
      sets: [...setIds.values()].filter((s) => used.has(s.id)).map(({ questionCount, _file, ...s }) => s),
      questions,
    };
    fs.writeFileSync(path.join(DIR, `${topic.slug}.json`), JSON.stringify(file, null, 1) + '\n');
  }

  return { topic, errors, warnings, count: questions.length, bySub, byDiff, posCount, sets: setIds.size };
}

function printResult(r, { verbose }) {
  if (r.skipped) return;
  const flag = r.errors.length ? '✗' : r.warnings.length ? '△' : '✓';
  console.log(`${flag} ${r.topic.slug.padEnd(34)} ${String(r.count).padStart(4)}/${r.topic.minQuestions}  e/m/h ${r.byDiff.easy}/${r.byDiff.medium}/${r.byDiff.hard}  answers A-D ${r.posCount.join('/')}  sets ${r.sets}`);
  const maxShow = verbose ? 999 : 12;
  r.errors.slice(0, maxShow).forEach((e) => console.log(`    ERROR  ${e}`));
  if (r.errors.length > maxShow) console.log(`    ... ${r.errors.length - maxShow} more errors`);
  r.warnings.forEach((w) => console.log(`    warn   ${w}`));
}

// --- main ---
const args = process.argv.slice(2);
const flags = new Set(args.filter((a) => a.startsWith('--')));
const slugs = args.filter((a) => !a.startsWith('--'));

if (flags.has('--report')) {
  let total = 0, target = 0, done = 0;
  for (const t of taxonomy.topics) {
    const dir = path.join(CHUNKS, t.slug);
    const n = fs.existsSync(dir)
      ? fs.readdirSync(dir).filter((f) => f.endsWith('.json')).reduce((acc, f) => {
          try { const j = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); return acc + (Array.isArray(j) ? j : j.questions || []).length; } catch { return acc; }
        }, 0)
      : 0;
    total += n; target += t.minQuestions; if (n >= t.minQuestions) done++;
    console.log(`${n >= t.minQuestions ? '✓' : n > 0 ? '△' : '·'} ${String(t.order).padStart(2)} ${t.slug.padEnd(34)} ${String(n).padStart(4)}/${t.minQuestions}  ${t.category}`);
  }
  console.log(`\n${done}/${taxonomy.topics.length} topics at quota — ${total}/${target} questions`);
  process.exit(0);
}

let topics = taxonomy.topics;
if (slugs.length) {
  topics = slugs.map((s) => {
    const t = taxonomy.topics.find((x) => x.slug === s);
    if (!t) { console.error(`Unknown topic "${s}". See content/aptitude/_taxonomy.json`); process.exit(2); }
    return t;
  });
} else if (!flags.has('--all') && !flags.has('--check')) {
  console.error('Usage: node scripts/buildAptitude.mjs <slug> | --all | --check | --report');
  process.exit(2);
}

let failed = 0, built = 0;
for (const t of topics) {
  const r = buildTopic(t, { write: !flags.has('--check') });
  if (r.skipped) { if (slugs.length) console.log(`· ${t.slug}: no chunks in _chunks/${t.slug}/`); continue; }
  built++;
  if (r.errors.length) failed++;
  printResult(r, { verbose: slugs.length === 1 });
}
console.log(`\n${built} topic(s) processed, ${failed} with errors.`);
process.exit(failed ? 1 : 0);
